### ISSUE TITLE
Create Program Page Save Function Redirect

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#101]
![Create Program Save Page](https://user-images.githubusercontent.com/48923883/55976548-74940c80-5c41-11e9-836f-f629ed7a0e39.png)

**Comment by BethRR** [comment]
Beth to create new issue. Current behavior does not refresh the page so user is unaware that they have created a program -- desired behavior is for page to refresh and display each time a new program is created. The problem with NOT doing this is that users will likely create many duplicates/garbage data.
