### ISSUE TITLE
User Management Page

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#102]
![User Management](https://user-images.githubusercontent.com/48923883/55977532-e5d4bf00-5c43-11e9-821f-1e2ba990cc9f.png)

**Comment by sunnytambi** [comment]
@akhilesh-94 , please check the page navigation all across the site and ensure that no page has a navigation blockage i.e. user should be able to navigate from one page to any other page with ease.

**Comment by akhilesh-94** [comment]
@JRWinWin one can navigate to 'Organization Management' page from the 'Menu' button. This option is accessible throughout the application

![image](https://user-images.githubusercontent.com/43365228/56356326-2b6e2a80-61f6-11e9-9ac9-7eb6f6cb25fa.png)

**Comment by BethRR** [comment]
There is still an issue with the filter button selection behavior on the User Management page

**Current behavior:** Selecting the Active filter button and then selecting the Inactive button results in BOTH Active and Inactive button selection unless user clicks on of those buttons a second time. All= Inactive and Active, so user does not need the ability to multi select buttons.

**Desired:** No multi select of the buttons is required (i.e., we'd like the user to only have one button selected at a time).
