### ISSUE TITLE
SDG Format

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#115]
![SDG Tag Format](https://user-images.githubusercontent.com/48923883/56234442-2bc1c680-603a-11e9-898e-dc54d9239659.png)

**Comment by BethRR** [comment]
@sunnytambi @akhilesh-94  Displaying the numbers is an essential part of how users understand the SDGs ( and hence our SDG tags). This is critical.

**Comment by akhilesh-94** [comment]
@BethRR This was already implemented. Seems to be an issue similar to   https://github.com/winwinwiki/winwin-frontend/issues/162#issuecomment-490172854. 
Could you please check.
