### ISSUE TITLE
Org Chart - Department within Division

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#118]
![Org chart - Department within a Division](https://user-images.githubusercontent.com/48923883/56235106-97f0fa00-603b-11e9-9be9-94d4bb5146e2.png)

**Comment by akhilesh-94** [comment]
We need to click on a division to see its departments

**Comment by BethRR** [comment]
@sunnytambi  @akhilesh-94 The core issue is that the org chart is not working as desired, although to be fair, the desired behavior hasn't been fully defined. The  issue logged here was trying to communicate the need to display the entire org chart. John and I are working on defining what is needed for the MVP to ensure the dataseeders can complete their tasks. More details to come. This issue will remain closed, but new issues or perhaps Trello tasks will be created that address fundamental requirements for the Org Chart features.
