### ISSUE TITLE
Org Chart - Org Level Title Edit

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#119]
![Org Level Title Edit](https://user-images.githubusercontent.com/48923883/56235627-a1c72d00-603c-11e9-9a59-3a4010b51dfe.png)

**Comment by BethRR** [comment]
This requirement is more complicated than it might appear. Beth to add more detail shortly.

**Comment by sunnytambi** [comment]
We are in process of restructuring the org chart layout.
However in any case, edits in org title wont be allowed.

**Comment by BethRR** [comment]
@sunnytambi - not fixing is okay for the MVP, but this is a required feature long term. We actually don't want to limit the levels OR have fixed labels for the long term. It's fine if these are defaults, but not as a fixed label/name.
