### ISSUE TITLE
Pagination feature not working as expected

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#147]
1)	Pagination feature not working as expected:
a.	Using the row selection dropdown to change the # of rows to display does not change the number of rows displayed, though it does change the page count
b.	User row count choice does not persist when user navigates to another page of the results and reverts to default (10 rows). This also changes the page count.

**Comment by akhilesh-94** [comment]
This feature is redundant

**Comment by sunnytambi** [comment]
@akhilesh-94 , please specify more details so that it can be closed

**Comment by akhilesh-94** [comment]
@BethRR @sunnytambi We already have the provision for pagination as shown below - 
![image](https://user-images.githubusercontent.com/43365228/57365448-b792c280-71a2-11e9-853a-0d27bb18c05e.png)
To maintain consistency across the table, the number of rows shown at a time should be fixed(i.e. 10 rows). So, the row count dropdown is not needed

**Comment by BethRR** [comment]
@akhilesh-94 @sunnytambi The proposed (and implemented) solution of setting a fixed row count doesn't work for us because allowing the user to set the number of rows is important for basic workflow, especially for admins who need to be able to perform actions on large numbers of items at a time. There are additional problems with pagination that aren't fixed by this approach (see bug #257 ), so it would be ideal fix this issue and allow user to select # of rows to display.
