### ISSUE TITLE
Regions Served : Search field should be available upon entering page ( for Admins and Dataseeders)

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#156]
Prefer that the search field be available to Admin and Dataseeder without the need for the Edit/Pencil button (Pri 3)

**Comment by BethRR** [comment]
@akhilesh-94 - Thanks for fixing this. Quick question: there is a significant lag between when the regions served page is opened and when the control appears (~4.5 seconds) Is this due to loading the regions in the list? Is there a way to speed up the loading of the control?

**Comment by akhilesh-94** [comment]
> @akhilesh-94 - Thanks for fixing this. Quick question: there is a significant lag between when the regions served page is opened and when the control appears (~4.5 seconds) Is this due to loading the regions in the list? Is there a way to speed up the loading of the control?

Yes, the lag is due to ~40k records being loaded at a time. But, we will be fixing that.
