### ISSUE TITLE
SPI Tag Edit Page: Search control not working at all

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#157]
Steps to repro:
1) Navigate to http://d3vudu8znrvs1z.cloudfront.net/organizations/39510/spi-tags and click on the pencil. This will launch the SPI Tag edit page. 
2) Try to type in the the search control. Note that the control does not accept any text.

Expected: That user can type in the search control and see tags related to their search bolded or highlighted in some way.

**Comment by akhilesh-94** [comment]
@BethRR I have implemented the search functionality as shown below - 
Eg. If a user is trying to search 'access' keyword, the resulting tags will be a filtered list of tags. 
This way the user is more focussed on the recommended tags.
![image](https://user-images.githubusercontent.com/43365228/57449764-5e965d80-727a-11e9-9f4b-70367b183573.png)

**Comment by BethRR** [comment]
Confirmed fix
