### ISSUE TITLE
Admin Console main page not rendering after log-in 

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#162]
Steps to repro:

1. Go to http://d3vudu8znrvs1z.cloudfront.net/organizations/39482 and login. 
2. Note that screen is blank. This is true in all browsers tested (Google, Firefox, Safari, and Edge).
3. Clear browsing history, cookies, etc. and repeat 1 & 2 -- note that behavior is the same.
4. Navigate to  http://d3vudu8znrvs1z.cloudfront.net/organizations/39482  -- note that it renders with as expected. 
5. Using the main menu, navigate to User Management and note that it renders as expected.
6. Using the main menu once again, select Organization Management and note that it renders as a blank page.

Attached is some error info captured from from browser:
[Chrome_error text.txt](https://github.com/winwinwiki/winwin-frontend/files/3149705/Chrome_error.text.txt)
[Firefox error text.txt](https://github.com/winwinwiki/winwin-frontend/files/3149706/Firefox.error.text.txt)

**Comment by akhilesh-94** [comment]
@BethRR Our code must be in between deployments, which might have caused this issue. 
Could you confirm if this issue is still there?
