### ISSUE TITLE
Organization SDG Tags Page: SDG's displayed incorrectly (sans number codes)

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#172]
To Repro: 
1. Navigation to: http://d3vudu8znrvs1z.cloudfront.net/organizations/37353/sdg-tags 
2. Note that the SDG's do not include their code number (e.g., 2 End Hunger or 2.3 Increase Agricultural Activity & Income)

Expected: That SDG code numbers would be displayed along with the text.

Justification: Users refer to the numbers at least as much as the text ( maybe more) and will need these codes.

**Comment by akhilesh-94** [comment]
Made the required changes

**Comment by BethRR** [comment]
confirmed fix
