### ISSUE TITLE
User Management: New users created by Admin unable to log in

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#180]
The admin (logged in as Sunny) added a new admin user (beth.roberts@winwin.care). The new admin user received email with instructions and password. The username and password didn't work and no errors were visible in the browser. 

The following might be noteworthy:
1)  the generated password contained a colon (maybe that was an unexpected char?) 
2) When I look in the database, I don't see beth or even sunny listed as users.

To repro to: Try logging into system as beth.roberts@winwin.care w/pw j:2YAhdy

**Comment by BethRR** [comment]
@akhilesh-94 this is still not working for us. John and I have be added as users. We get an email, but we are never able to log in/change our password with the credentials sent to us.

**Comment by akhilesh-94** [comment]
@BethRR I am not able to reproduce this issue. Could you please help me the screenshot of the mail(containing the password)?
