### ISSUE TITLE
User Management: No way for user with expired temporary password to have new temp password assigned

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#181]
A new user was added and received an email with temp password. The new user didn't see the email until after the password had expired. Predictably, user was unable to log-in and contacted the admin for another password. The admin saw the user in the user management, but cannot push a new password to them.  We tried the lost password route, but the user never received an email, though one is required to complete the process

**Comment by akhilesh-94** [comment]
@BethRR In order to push a new password to the user, admin needs to create that user again with the same emailId.
