### ISSUE TITLE
System email address needs to be changed to look less like spam

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#182]
Currently, new winwinwiki users that have just been added to the system get an email from 
'no-reply@verificationemail.com' -- this looks like spam and thus ends up in junk or being ignored. What are our options for changing this name? Can we change this to no-reply-admin@winwin.care?

**Comment by akhilesh-94** [comment]
@BethRR  **no-reply-admin@winwin.care** needs to a valid email address for AWS Cognito to verify it in order to change the FROM address. If it is a valid email address, I have triggered a verification email for the same.
![image](https://user-images.githubusercontent.com/43365228/58092787-a017f880-7bea-11e9-82eb-41633e8b1851.png)

**Comment by BethRR** [comment]
@akhilesh-94 That email should be working bow, please let me know if this issue persists

**Comment by akhilesh-94** [comment]
> @akhilesh-94 That email should be working now, please let me know if this issue persists. It looks like new users still get mail from [no-reply@verificationemail.com](mailto:no-reply@verificationemail.com)

I have resent the verification mail, could you please check and verify it?
![image](https://user-images.githubusercontent.com/43365228/58855952-f0995680-86be-11e9-8608-1da51397747a.png)

**Comment by BethRR** [comment]
@akhilesh-94 I just verified the email with AWS so this should be working. Please let me know if you have any other issues.

**Comment by arvindkhatik012** [comment]
We have resolved the issue now. Please find the attached screenshot for reference.
![from_email_address](https://user-images.githubusercontent.com/45760420/61270131-54369980-a7be-11e9-9e59-292383efa58f.JPG)

**Comment by BethRR** [comment]
Confirmed fix and closing.
