### ISSUE TITLE
Org Management Filter for High Priority

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#193]
Repro:
1. On the Org Management page, check the Action Check Boxes on at least one organization.
2. Select High Priority in the Actions dropdown to change check boxed organizations.
3. Open the Filter Menu, select the High Priority filter.
4. No results remain once the filter is applied. 
5. Remove the High Priority filter
6. Once removed, the High Priority organizations have been reset to Normal. 

Expected: 
1. Organization Management filter should work for the High Priority/Normal fields.
2. The High Priority setting should remain after the filter function has been used.

**Comment by akhilesh-94** [comment]
@JRWinWin @BethRR Unable to reproduce. Could you please check again if the issue is still there?

**Comment by JRWinWin** [comment]
@akhilesh-94 I am also unable to reproduce this issue currently

**Comment by akhilesh-94** [comment]
@JRWinWin Might be an issue that occurred when the code was in between deployments.
