### ISSUE TITLE
User/Organization Management Search Function

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#194]
![User Management Seach Function](https://user-images.githubusercontent.com/48923883/57956149-e4369080-78ac-11e9-8622-c08a3dd415cd.png)

![User Management Search Function Not Working](https://user-images.githubusercontent.com/48923883/57956251-3d062900-78ad-11e9-87a7-2cd328c1486c.png)

Repro:
1. On either the Organization or User Management pages, attempt a search with a capitalized letter. Search using "A" instead of "a". 
2. The search will not work. This issue is present on BOTH Organization management and User management pages.

Expected:
Users should have the ability to search using both lowercase and uppercase letters.

**Comment by akhilesh-94** [comment]
Made the required changes
