### ISSUE TITLE
Organization Management Filter Removal

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#196]
![Organization Management Filter Removal Screen #1](https://user-images.githubusercontent.com/48923883/57957511-61fc9b00-78b1-11e9-92e5-c907dd1419dd.png)
![Organization Management Filter Removal Screen #2](https://user-images.githubusercontent.com/48923883/57957517-645ef500-78b1-11e9-9390-8b13dfdaabf8.png)

Repro:
1. On the Organization Management page, apply multiple filters. 
2. Remove those filters. The organizations do not re-populate once the filters are removed. 

Expected: Once a filter is removed, the organizations that were previously hidden due to that filter should repopulate. When all filters are removed, all organizations should be repopulated.

**Comment by akhilesh-94** [comment]
@JRWinWin @BethRR  Could you please check if revenue and assets (the range sliders) filter are reset as well? 
Need to click on the **Reset Filters**  button to reset range sliders
![image](https://user-images.githubusercontent.com/43365228/57973082-de31d400-79c0-11e9-9f0c-ac5cde608075.png)

**Comment by JRWinWin** [comment]
@akhilesh-94 
To clarify the original issue:

Repro:

1. On the Organization Management page, apply multiple filters.
2. Remove those filters **by clicking the "x" on each filter**. The organizations do not re-populate once the filters are removed.

Note: Selecting "Reset Filters" or "Clear all Filters" results in the desired function. 

Expected: Once a filter is removed, the organizations that were previously hidden due to that filter should repopulate. When all filters are removed, all organizations should be repopulated.
