### ISSUE TITLE
Org Management Search Bar

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#210]
![Org Management Page - Search Text](https://user-images.githubusercontent.com/48923883/58136567-64c5fb80-7be3-11e9-9bc6-f9e4d907cb56.png)
![Org Management Search - Searching Org Name and City Fields?](https://user-images.githubusercontent.com/48923883/58136576-68598280-7be3-11e9-830f-ec41775dced6.png)

Question: It appears that the Organization Management Search Bar is searching the Organization Name and City. Is this correct? If so, the ghost text in the Org Management Search Bar ("Search State/County/City/District") should be changed to accurately reflect the fields that the Search Bar is searching.

**Comment by akhilesh-94** [comment]
@JRWinWin Correct, I am planning to remove the search bar in **Organization Name** column. 
Hope that won't be an issue.
![image](https://user-images.githubusercontent.com/43365228/58153901-e5d9cd00-7c8d-11e9-8ffa-e2ea21bdf9d3.png)

**Comment by BethRR** [comment]
@akhilesh-94  - the organization search/filter seems to find more results than the search at the top of the page, so we'd like to keep it if possible. An example of the difference: 
Searching on 'dog' in the search at the top of the page yields no results, whereas searching on 'dog' in the organization search yields 'Doğuş Group ! ?12 & Beyond the realm of men', which is the expected result.

**Comment by akhilesh-94** [comment]
> @akhilesh-94 - the organization search/filter seems to find more results than the search at the top of the page, so we'd like to keep it if possible. An example of the difference:
> Searching on 'dog' in the search at the top of the page yields no results, whereas searching on 'dog' in the organization search yields 'Doğuş Group ! ?12 & Beyond the realm of men', which is the expected result.

I have tried fixing it could you please test the search at top of the page again?

**Comment by JRWinWin** [comment]
@akhilesh-94 The top search bar with ghost text "Search State/City/County/District" is not currently functioning
