### ISSUE TITLE
Tag Status Filter Not Working

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#211]
![Tag Status Filter Not Working](https://user-images.githubusercontent.com/48923883/58136921-c63a9a00-7be4-11e9-905d-5b9719a2ecf9.png)

Repro: 
1. Apply the tag status filter in Filter management
2. The filter does not work

Expected: When a tag status filter is applied, the Organization list should reflect the action of the filter.

**Comment by JRWinWin** [comment]
I cleared my cookies and restarted the MVP. The filter function now works. My new question is: Why did it stop working?

**Comment by akhilesh-94** [comment]
> I cleared my cookies and restarted the MVP. The filter function now works. My new question is: Why did it stop working?

Sure, will look into it
