### ISSUE TITLE
Notes Section Edit Option

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#225]
![Notes Edit Options](https://user-images.githubusercontent.com/48923883/58273574-d8801980-7d45-11e9-98dc-e8afb1a133eb.png)

Expected: Please add an Edit Pencil and accompanying Edit function to the Notes page.

**Comment by akhilesh-94** [comment]
@JRWinWin will be doing this post-MVP

**Comment by akhilesh-94** [comment]
@JRWinWin Please create a new note, whenever there is a need to edit an old note
