### ISSUE TITLE
Regions Served List Order Question

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#234]
![Regions Served List Order](https://user-images.githubusercontent.com/48923883/58515536-03a9a500-815a-11e9-8caa-adc156f684e0.png)

**Comment by akhilesh-94** [comment]
@JRWinWin They are ordered alphabetically

**Comment by JRWinWin** [comment]
@akhilesh-94 If you look at the photo I posted to this issue, those results are not alphabetically ordered.

**Comment by akhilesh-94** [comment]
> @akhilesh-94 If you look at the photo I posted to this issue, those results are not alphabetically ordered.

@JRWinWin I am not able to reproduce this issue. Did you search for a specific region which filtered the list?

**Comment by JRWinWin** [comment]
@akhilesh-94 I did not search for a specific region (there is no text in the photo), I just scrolled down the list once the text entry box is selected. The list was unfiltered. The list looks alphabetical initially but then upon a scroll, the alphabetization stops.

**Comment by akhilesh-94** [comment]
As of now, the functionality will be as per discussion on [slack](https://winwin2016.slack.com/archives/G8HRS371P/p1560756630102900?thread_ts=1560586087.099500&cid=G8HRS371P)

**Comment by akhilesh-94** [comment]
@JRWinWin Could please check if this issue still persists
