### ISSUE TITLE
View History - Organization Chart

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#238]
Expected: Changes made in the Organization Chart should be documented in the View History section. For the MVP, any change/update made in the Organization Chart should be documented in View History. Ideally, each potential change in Organization Chart (creation, deletion, edit) should be precisely documented in View History.

**Comment by akhilesh-94** [comment]
> Expected: Changes made in the Organization Chart should be documented in the View History section. For the MVP, any change/update made in the Organization Chart should be documented in View History. Ideally, each potential change in Organization Chart (creation, deletion, edit) should be precisely documented in View History.

@JRWinWin According to the discussions we had, in **Organization Chart** we have **create** and **edit** operations only.

**Comment by JRWinWin** [comment]
@akhilesh-94 Yes, according to our discussion those are the operations within Organization Chart. This issue is in reference to View History. We would like changes made in Organization Chart to be recorded on the View History page. For the MVP, any change (create/edit) should be recorded on the View History page.

**Comment by akhilesh-94** [comment]
@JRWinWin @BethRR Whenever a child organization is created, it's history is logged in associated to it's immediate parent organization.

**Comment by JRWinWin** [comment]
@akhilesh-94 This issue is not resolved. 
Here is what we want: When a change is made to **Egg**, it should be recorded in the View History of **This node has dragging disabled**. The View History is a log of changes made within a given organization. **Egg** is a child organization (although not a direct child) of **This node has dragging disabled**, therefore it is within the given organization of **This node has dragging disabled**, so any Org Chart change made to **Egg** should be recorded in **This node had dragging disabled**.

**Comment by arvindkhatik012** [comment]
Hi @BethRR ,

**Comment by BethRR** [comment]
@arvindkhatik012  - what does the invalid label mean?

**Comment by BethRR** [comment]
@akhilesh-94 -- now that we are saving root parent for each org this should be feasible. Adding back to To-Do.

**Comment by JRWinWin** [comment]
This issue has been resolved
