### ISSUE TITLE
Organization Management - Disabled Functions

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#24]
![Org Management - Disabled Filter Functions](https://user-images.githubusercontent.com/48923883/54949667-d132c000-4efc-11e9-92ad-dd1f2f211052.png)

Main Org Management page functions that do not currently work.

**Comment by akhilesh-94** [comment]
We can search in the organization table by organization name now.

**Comment by JRWinWin** [comment]
Great yes that works now. The Sector filter still does not work and the location search filter still does not work

**Comment by akhilesh-94** [comment]
> Great yes that works now. The Sector filter still does not work and the location search filter still does not work

Still working on it.
