### ISSUE TITLE
Organization Details - Basic Information - Sector Level Grey Out

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#25]
![Org Details - Basic Information - Sector Level Grey Out](https://user-images.githubusercontent.com/48923883/54949799-1656f200-4efd-11e9-8603-2a8c940de9d0.png)

Can we grey out sector level when Private or Social is selected for Sector?

**Comment by akhilesh-94** [comment]
@JRWinWin According to my understanding if 'Sector' is not 'Public' then 'Sector Level' and 'Sector Level Name' will be disabled. Is that correct?

![image](https://user-images.githubusercontent.com/43365228/55789360-d6386780-5ad7-11e9-91c5-e440143e84d3.png)

**Comment by JRWinWin** [comment]
Yes that is correct
