### ISSUE TITLE
Region Served dropdown: Cannot add new location

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#251]
Steps to Repro:
1) Navigate to http://d3vudu8znrvs1z.cloudfront.net/organizations/37189/programs/41883/regions-served
2) Type 'Pullman Region' into the control and note that there are no results
3) Hit enter on keyboard and note that nothing happens

EXPECTED: New location named "Pullman Region" would be added to the list of regions served AND would appear in the results when I subsequently entered 'Pullman Region'. 

ACTUAL: 'Pullman Region' not created and not added to the list.

**Comment by JRWinWin** [comment]
@akhilesh-94 We are still experiencing this issue

**Comment by JRWinWin** [comment]
@akhilesh-94 Still not fixed yet

**Comment by akhilesh-94** [comment]
Searching regions or creating new regions should have a **minimum length of 3 characters**. This is required to keep the **Regions Served** page more efficient.
For eg.
Whenever a text (in our case **tri** ) is entered (with no. of characters >=3), a list of suggestions will be shown in the dropdown with an extra options at the end of the list to create new a region (i.e. **Create 'tri'**), as shown below
![image](https://user-images.githubusercontent.com/43365228/60259131-27484280-98f4-11e9-8203-0be03f3d50b9.png)

**Comment by BethRR** [comment]
confirmed fixed
