### ISSUE TITLE
Forget Password page not working

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#255]
If a user forgets their password and then enters their email in the forget password page, they never receive an email to reset password. It appears that the page never actually kicks off an email to the user.

**REPRO STEPS:**
1.  On the sign in page click 'Forget Password?' or navigate directly to http://d3vudu8znrvs1z.cloudfront.net/forget-password
2.  Enter your email and click 'Send confirmation' button.
3.  Check your email and note that you do not receive the confirmation

**Two errors in in console:** 
1) POST http://ec2-54-209-46-206.compute-1.amazonaws.com/user/resetPassword 400
2) Uncaught (in promise) SyntaxError: Unexpected end of JSON input at c (api.js:9)
c @ api.js:9
Promise.then (async)
c @ api.js:10
Promise.then (async)
(anonymous) @ api.js:35
r @ api.js:4
(anonymous) @ forgetPasswordAction.js:7
(anonymous) @ index.js:8
(anonymous) @ redux.js:449
value @ index.js:117
i @ react-dom.production.min.js:14
a @ react-dom.production.min.js:15
s @ react-dom.production.min.js:15
l @ react-dom.production.min.js:17
p @ react-dom.production.min.js:18
g @ react-dom.production.min.js:18
d @ react-dom.production.min.js:18
v @ react-dom.production.min.js:21
Le @ react-dom.production.min.js:84
yr @ react-dom.production.min.js:231
K @ react-dom.production.min.js:39
Be @ react-dom.production.min.js:86
_r @ react-dom.production.min.js:232
ze @ react-dom.production.min.js:85

**Comment by JRWinWin** [comment]
![Screen Shot 2019-06-18 at 5 42 42 PM](https://user-images.githubusercontent.com/48923883/59728823-828d7d00-91f0-11e9-8c35-fd618c65c56f.png)

We are still experiencing this issue

**Comment by BethRR** [comment]
confirmed fixed
