### ISSUE TITLE
Org Management Page: Result count should display <1-# of results displayed on current page> of <TOTAL count of results> 

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#256]
The Organization Management page should be displaying <1-#> of <TOTAL count of results>, but is instead displaying only the number of organizations on the active page.  For example: in the attached screenshot, "1-10 of 20 organizations found" should be displayed rather than "10 organizations found"  .
![ResultsCountIssue](https://user-images.githubusercontent.com/49886260/58820799-6aaadc00-85e8-11e9-84e1-aa9970b229da.png)

**Comment by akhilesh-94** [comment]
> The Organization Management page should be displaying <1-#> of , but is instead displaying only the number of organizations on the active page. For example: in the attached screenshot, "1-10 of 20 organizations found" should be displayed rather than "10 organizations found" .
> ![ResultsCountIssue](https://user-images.githubusercontent.com/49886260/58820799-6aaadc00-85e8-11e9-84e1-aa9970b229da.png)

According to our discussions, '10 Organizations found' is supposed to show only the total organizations being shown (filtered/unfiltered). The "1-10 of 20 organizations found" is redundant as this information is already being indicated by the page number indicator at the bottom of the table.

**Comment by BethRR** [comment]
@akhilesh-94 this wasn't fixed in the way that was requested, but we can live with it for the MVP.
