### ISSUE TITLE
Org Management Page: Pagination not working correctly with filters

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#257]
When applying a filter on org management the result count and the display of the results does not work as expected. Though the pages are currently coded to show 10 rows, a set of 7 results is displayed across two pages with 4 on page one and 3 on the other ( see attached screenshot). This is made further confusing by bug #256. 

REPRO STEPS:
1. Navigate to http://d3vudu8znrvs1z.cloudfront.net/organizations
2. Click on Public to select the Public sector filter.
3. Note that there are two pages of public sector organizations with only 4 organizations on page one.
4. Click Next button to view page two and note that there are only 3 organizations on page two

EXPECTED: All seven organizations would appear on page one.
ACTUAL: Seven results are spread across two pages.

See attached screenshot
![PaginationFilterIssue](https://user-images.githubusercontent.com/49886260/58821960-21a85700-85eb-11e9-99a6-a15f01918361.png)

**Comment by akhilesh-94** [comment]
This is an in-progress task.
