### ISSUE TITLE
Organization Creation - Tag Status Assignment

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#265]
Repro: 
1. Create an organization
2. View organization in Organization Management with an "R" in the Tag Status column
3. Select Organization and see that its Tag Status is blank. Tag Status is not a field in Create Organization, so it must be assigned automatically upon creation. It is currently being left blank  in the data, but represented by "R" in Organization Management.

Expected: Once an organization is created through the Single Organization Creation option, "Unfinished Tag" should be entered automatically in the Tag Status field. The Tag Status column in Organization Management should be represented by a "U" accordingly. 

![Organization Management Tag Status Assignment](https://user-images.githubusercontent.com/48923883/58910573-b5048980-86ca-11e9-97a6-eca7751ee99c.png)
![Org Basic Info Tag Status Assignment](https://user-images.githubusercontent.com/48923883/58910582-bb930100-86ca-11e9-9c9e-46493e6096f3.png)

**Comment by akhilesh-94** [comment]
> Repro:
> 
> 1. Create an organization
> 2. View organization in Organization Management with an "R" in the Tag Status column
> 3. Select Organization and see that its Tag Status is blank. Tag Status is not a field in Create Organization, so it must be assigned automatically upon creation. It is currently being left blank  in the data, but represented by "R" in Organization Management.
> 
> Expected: Once an organization is created through the Single Organization Creation option, "Unfinished Tag" should be entered automatically in the Tag Status field. The Tag Status column in Organization Management should be represented by a "U" accordingly.
> 
> ![Organization Management Tag Status Assignment](https://user-images.githubusercontent.com/48923883/58910573-b5048980-86ca-11e9-97a6-eca7751ee99c.png)
> ![Org Basic Info Tag Status Assignment](https://user-images.githubusercontent.com/48923883/58910582-bb930100-86ca-11e9-9c9e-46493e6096f3.png)

Should the priority status be set to **Normal**, on create of org along with **Unfinished** tag

**Comment by JRWinWin** [comment]
@akhilesh-94 Yes, that is correct.
