### ISSUE TITLE
Child Organization Chart

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#272]
![Org Chart View](https://user-images.githubusercontent.com/48923883/59119613-17969900-8908-11e9-97d3-9167f6eae2a7.png)

Repro:
1. Go to the Path with Art Organization Chart
2. Select Classes
3. Open the Classes Organization Chart. It will contain just Classes. 
![Child Org Organization Chart](https://user-images.githubusercontent.com/48923883/59119649-2c732c80-8908-11e9-9298-b0cfea469bbe.png)

Expected: A child organization ("Classes") is a part of the parent organization ("Path with Art"), so it should have the same Organization Chart as its parent. The Organization chart from the parent should be displayed as the Organization Chart for all of its children.

**Comment by akhilesh-94** [comment]
@JRWinWin According to our discussions, the expected behavior is when a user selects a node ("Classes") in the tree structure, the context of the application gets set to the clicked node (i.e. now the current organization set to "Classes" from previously "Path with Art"). So, now the parent organization will be "Classes" not "Path with Art". The tree will only show its children.

**Comment by BethRR** [comment]
@akhilesh-94 @sunnytambi  - This is actually a pretty significant problem in that without this feature  it's too easy to be utterly lost when you've hit the leaf node and have no context -- it's currently impossible  to traverse an org in the tool. We need a way for users to navigate to the orgs immediate parent when there is one.

**Comment by BethRR** [comment]
@arvindkhatik012 @sunnytambi @akhilesh-94 - Did you read my note? We have **no** way to navigate to parents which is very disorienting when entering or updating information. We need some way to navigate to the immediate parent as there is not a workaround. So, this cannot be put off to post mvp.

**Comment by akhilesh-94** [comment]
> @arvindkhatik012 @sunnytambi @akhilesh-94 - Did you read my note? We have **no** way to navigate to parents which is very disorienting when entering or updating information. We need some way to navigate to the immediate parent as there is not a workaround. PRI 1 items cannot be moved to post-mvp without agreement by winwin.

As for now, we can click on the browser's back button to navigate back. We can come up with a efficient solution for this post-MVP.

**Comment by sunnytambi** [comment]
Hi @BethRR , @JRWinWin , this feature was already discussed and parked into Post MVP bucket in Trello.
https://trello.com/c/NlIught8/40-org-chart-breadcrumb

I am removing design-issue label from this ticket and adding post-mvp to it.

**Comment by BethRR** [comment]
As a rule, nothing should be moved to Post-MVP without agreement and discussion between WinWin and Talentica. This is one of may issues that were moved to Post-MVP without any discussion with us. We didn't consider this a post-MVP item until there was a workaround in place.
