### ISSUE TITLE
Program List Page - No Programs message

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#289]
![Program List - No Programs message](https://user-images.githubusercontent.com/48923883/59300699-ae36c300-8c44-11e9-9a51-46c107cf3254.png)

Repro:
1. Select an Organization with no Programs. The message displayed will read "No programs containing your search terms were found". In this instance, there were no search terms entered making this message confusing for the user. 

Expected: If there are no programs created for an organization, the message should read "There are no programs within this organization". If a user enters a search that provides no results, then the message shown should be the current message, "No programs containing your search terms were found"

**Comment by akhilesh-94** [comment]
@BethRR I am planning to keep a universal message as **"No programs were found"**, as the search is API based, it would be difficult for me at client-side to differentiate between messages.

**Comment by JRWinWin** [comment]
@akhilesh-94 That is a better message, thanks.
