### ISSUE TITLE
Create User - Role Options

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#291]
![Create User - Role Options](https://user-images.githubusercontent.com/48923883/59313916-b522fd00-8c67-11e9-9612-3e30393bcc7e.png)

Question: Where did this Role option come from? We did not discuss this option for User roles. 
Expected: Only two User roles are available, Administrator and Data Seeder.

**Comment by BethRR** [comment]
confirmed fix
