### ISSUE TITLE
SDG Tagging not Working

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#294]
Repro: 1. Navigate to any organization or program and add at least one SDG tag.
2. Navigate away from that page to any location.
3. Reopen the SDG tagging page within the selected organization/program. The SDG tags that were previously selected are gone. 
Here is the accompanying error message in Inspect -> Console: 
ec2-54-209-46-206.compute-1.amazonaws.com/user/update:1 Failed to load resource: the server responded with a status of 400 ()
api.js:9 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at c (api.js:9)
ec2-54-209-46-206.compute-1.amazonaws.com/user/login:1 Failed to load resource: the server responded with a status of 400 ()
2ec2-54-209-46-206.compute-1.amazonaws.com/organization/69/sdgdata:1 Failed to load resource: the server responded with a status of 405 ()
ec2-54-209-46-206.compute-1.amazonaws.com/program/42674/sdgdata:1 Failed to load resource: the server responded with a status of 405 ()
3ec2-54-209-46-206.compute-1.amazonaws.com/organization/41028/sdgdata:1 Failed to load resource: the server responded with a status of 405 ()

Expected: SDG Tagging should be functional and changes made should be recorded in View History

**Comment by BethRR** [comment]
@akhilesh-94 @arvindkhatik012  - We are still experiencing this issue.

**Comment by akhilesh-94** [comment]
@BethRR @JRWinWin Could you please check again. I have checked on [http://dev.winwin.care/](http://dev.winwin.care/) it's working for me

**Comment by JRWinWin** [comment]
@akhilesh-94 The problem has been resolved.
