### ISSUE TITLE
Upload Data Feed - Outdated Template File for Download

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#295]
Repro: 1. Navigate to the Upload Data Feed page.
2. Download the Template file for upload. It will download an outdated version of the Template file. 

Expected: The file download should match our latest version of the Upload template.

**Comment by akhilesh-94** [comment]
@BethRR The filename for the template in **winwin-public-bucket-dev** bucket is **admin_bulk_create_template.csv**

**Comment by BethRR** [comment]
@akhilesh-94  -- the download template button in the application points to Upload_bulk_org_template.csv, not admin_bulk_create_template -- so it does NOT get the new template. 

We also learned that it does not work to drop a file with the referenced name into the buket. I made a copy of admin_bulk_create_template.csv, renamed it to Upload_bulk_org_template.csv and uploaded it to the winwin-public-bucket-dev, so now there is a file there with the name referenced in the UI -- BUT @JRWinWin continues to get the old template when he clicks download.

I, on the other hand, always get the following error for which I am logging a separate bug but include here in case it might be helpful: 
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6E6DE8334CB479D3</RequestId>
<HostId>
TsjbKn2Cz0sZZo7Y4kriqSh5TV3rtwhqKgp6+D5sJR6pGhb69vcNCsgYUWTHCFcCEBhh4O4ucys=
</HostId>
</Error>

**Comment by akhilesh-94** [comment]
We need to make the file public to be made accessible to the UI

**Comment by BethRR** [comment]
@akhilesh-94 -- I am very new to AWS and still learning, but it looks to me like that folder and all of its contents are already public. Is that incorrect? It's still curious to me that John could have been downloading a file that wasn't even present in the directory --- maybe there is load balancer/cdn cache that needs to be cleared?

**Comment by akhilesh-94** [comment]
> @akhilesh-94 -- I am very new to AWS and still learning, but it looks to me like that folder and all of its contents are already public. Is that incorrect? It's still curious to me that John could have been downloading a file that wasn't even present in the directory --- maybe there is load balancer/cdn cache that needs to be cleared?

As of now, we are hardcoding the path of the template (i.e. **Object URL**): 
![image](https://user-images.githubusercontent.com/43365228/59455291-7ccf1a80-8e31-11e9-924f-ef635f91b804.png)

When a new file is uploaded in a public bucket, the file is by default in private scope(as shown below) and needs an authenticated route to access it. In our case, we need public access to the file, to achieve that we need to click on **Make public** button as shown above(or from the **Permissions** tab).
![image](https://user-images.githubusercontent.com/43365228/59455833-9cb30e00-8e32-11e9-8e4f-15fe174602a5.png)
