### ISSUE TITLE
Upload Data Feed - Not Working

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#296]
Repro: 1. Upload procedure works (with the correct upload template) through UI Process. Browse and drag & drop features work. The selected file appears once it is loaded into the UI. 
2. After selecting "Upload", the uploaded organizations are not present in Organization Management or in the database. 

Expected: The uploaded organizations need to be present in Organization Management after the uploading process.

**Comment by JRWinWin** [comment]
@akhilesh-94 @arvindkhatik012 
Here is the error message that occurs after an attempted upload: 
![Screen Shot 2019-06-13 at 12 15 20 PM](https://user-images.githubusercontent.com/48923883/59461090-6abf8e80-8dd5-11e9-8b86-8769b9ea0b0c.png)
I will post the sample file on Slack that you should use to test the Upload feature through the UI.

**Comment by akhilesh-94** [comment]
@JRWinWin Changes were yet to be reflected. Could you please check again

**Comment by JRWinWin** [comment]
@akhilesh-94 The upload function does work in some instances. This particular issue is now outdated and further issues regarding the Data Upload feature have been logged.
