### ISSUE TITLE
Organization Basic Info: Add typeahead/search to NAICS and NTEE fields just as control works in filter on org mgmt page

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#304]
This is important to ensure that users can more easily find and select the right codes. It should work the same as the dropdown control used  in the filter on org mgmt page. 

![IndustryClass_Filter](https://user-images.githubusercontent.com/49886260/59456092-72c60100-8dca-11e9-9f7b-91f9bd4bdc7f.png)

**Comment by akhilesh-94** [comment]
Hi, @BethRR we will be doing this post-MVP.

**Comment by BethRR** [comment]
Hi @akhilesh-94 can you comment on the level of effort required to use the same control as is used in the filter as a selection control for this page?

**Comment by BethRR** [comment]
Hi @akhilesh-94 can you comment on the level of effort required to use the same control as is used in the filter as a selection control for this page?

**Comment by BethRR** [comment]
Hi @akhilesh-94 can you comment on the level of effort required to use the same control as is used in the filter as a selection control for this page?

**Comment by BethRR** [comment]
confirmed fixed
