### ISSUE TITLE
Organization Chart needs Delete Function

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#305]
![Org Chart Delete Function](https://user-images.githubusercontent.com/48923883/59458164-c8041180-8dce-11e9-8c48-87323fccf3fc.png)

Expected: Organization Chart needs a delete function. There is currently no way to delete child organizations.

**Comment by akhilesh-94** [comment]
@BethRR @JRWinWin https://github.com/winwinwiki/winwin-frontend/issues/238#issuecomment-497374671 According to our discussion will be taking this up post-MVP.

**Comment by BethRR** [comment]
@akhilesh-94 the problem with moving this post MVP is that we create garbage data with any mistake and we can't correct/resolve it.

**Comment by BethRR** [comment]
Confirmed that delete works. It also deletes all children contained within the deleted org.
