### ISSUE TITLE
Organization Management "Clear All Filters" with no filters

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#306]
![Org Mgmt Filter Applied](https://user-images.githubusercontent.com/48923883/59466306-e1628900-8de1-11e9-96cf-bc1eb976b790.png)
![Org Mgmt Clear All Filters Remain](https://user-images.githubusercontent.com/48923883/59466312-e4f61000-8de1-11e9-8e26-52abf33c5616.png)

Repro:
1. Apply any filter to Organization Management
2. Remove the filter via the "x" on the filter. The "Clear All Filters" button will remain after all filters have been removed.

Expected: The "Clear All Filters" button should only be present when there are filters applied to the Organization Management list. The "Clear All Filters" button should be removed when all filters are removed.

**Comment by akhilesh-94** [comment]
@JRWinWin I am not able to reproduce this issue

**Comment by JRWinWin** [comment]
@akhilesh-94 Yep I can't reproduce it anymore today so I will close
