### ISSUE TITLE
Org details > Org hierarchy data is not correct

### ISSUE THREAD

**Issue by sunnytambi** [winwinwiki/winwin-frontend#32]
![image](https://user-images.githubusercontent.com/712304/55343038-ddec8080-54c7-11e9-9d3f-bed8cebde1b7.png)

When user navigates into Org details, its org hierarchy list should be updated with current organization specific hierarchy.

**Comment by akhilesh-94** [comment]
Breadcrumb has been hidden for now, as in [#74](https://github.com/winwinwiki/winwin-frontend/issues/74)
