### ISSUE TITLE
MVP Operating Speed/Unable to Navigate - CRITICAL

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#330]
The MVP is operating at a very slow speed.
I was attempting to test the console and each click was taking 3-5 times longer to process than normal operating speeds.
After a few minutes of slow operation, I am now unable to navigate through the console at all. 
I have cleared cookies/caches and it has had no effect.
This issue is critical.

**Comment by akhilesh-94** [comment]
Servers are not responding. We are looking into it

**Comment by sunnytambi** [comment]
@JRWinWin, we found the speed to be up to the mark. Can you check if the issue is still there?
