### ISSUE TITLE
Bulk Creation: Autotagging writing ntee values into the naisc field and vice versa

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#346]
Previously (around Jun 14) the autotagging was working correctly, but **now** it appears that the upload logic is writing ntee values into the naisc field and writing naisc values into the ntee field.

We confirmed that the column orders match in the template download from the tool and the file uploaded.

Attached is saved results from the db or you can use the following query to see the same results:
SELECT * FROM public.organization where name like '%Canine Action%' order by updated_at desc

Note: the site was accessed via dev.winwin.care and the db is winwindb-dev
[Autoagging_Issue_Example_CSV.txt](https://github.com/winwinwiki/winwin-frontend/files/3336884/Autoagging_Issue_Example_CSV.txt)

**Comment by arvindkhatik012** [comment]
we have resolved the issue "upload logic is writing ntee values into the naisc field and writing naisc values into the ntee field"
