### ISSUE TITLE
User Management: Cannot create user unless I create them first in cognito (and then quickly add user to tool)

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#365]
This is related to #363 (unable to create new user)

1. As a test for resolving issue 363, I added a user (john.raynolds@winwin.care) directly into Cognito. 

2. Then I went into the Wiki Editor to try to add him to the tool user group and assign his role, but was unable to -- the error message said that I couldn't add him because he already existed, even though he did not exist in the tool. 
NOTE: As it happens, John had received the invitation and immediately attempted to login. He was able to login but got a blank page, presumably because he has no role. 

3. Then I deleted him in Cognito and started over again. I created john's account in Cognito, but this time logged into the tool before he could respond to the invitation and this time I was able to create his account.

**Expected:** Admin should *not* have to create a user's account in Cognito and then in the tool -- they should be able to simply create accounts in the tool.

**Actual:** Admin was required to create account within Cognito interface and then very quickly add them to the tool.

**Comment by akhilesh-94** [comment]
Now that #363 is resolved, this issue should be fixed too. If not, please let me know
