### ISSUE TITLE
Org details > Resources > Delete resource alert must contain user friendly message

### ISSUE THREAD

**Issue by sunnytambi** [winwinwiki/winwin-frontend#37]
![image](https://user-images.githubusercontent.com/712304/55386293-cf947800-554c-11e9-88dd-84601e31821c.png)

The alert message must contain "name" of the resource which is getting deleted.
Same goes to any other delete operation including data set, SPI tag, SDG tag, etc..

**Comment by akhilesh-94** [comment]
Changed the content of modal in Data-Sets, Resources and Org List
