### ISSUE TITLE
Regions Served Processing "Enter" Button

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#372]
Repro:
1. Enter at least 3 letters into the Regions Served entry field
2. Press "Enter" while the UI is producing the list based on the 3 letters. Pressing "Enter" functionally cancels the Regions Served search procedure. It will reset the Regions Served page and produce no results.

Expected: Pressing "Enter" while the Regions Served API is processing should yield no effect. Users might press "Enter" to speed up actions on the page, so it must not reset their entered search.

**Comment by sunnytambi** [comment]
@akhilesh-94 , please check it and try to fix.

**Comment by JRWinWin** [comment]
This issue has been resolved
