### ISSUE TITLE
Incorrect Download Template File

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#374]
Issue: For the bulk upload, the template that a user can download from the UI is an incorrect file type. I attempted to upload a file that had been downloaded through the UI and I got the attached error message. 
![Screen Shot 2019-07-01 at 1 22 06 PM](https://user-images.githubusercontent.com/48923883/60467931-db0b4400-9c0c-11e9-8329-3ef21610e743.png)

Expected: The downloadable file template should be the correct file type for uploading bulk data. The upload process requires CSV UTF-8 so the downloadable file template should also be CSV UTF-8

**Comment by akhilesh-94** [comment]
HI @BethRR, as we have checked the downloadable file template is in **UTF-8** encoding with an **.csv** extension, which is desired.
After downloading the template and **after adding data to the empty excel**, please check if the encoding is correctly set to UTF-8 (we have found that the encoding gets changed sometimes) and the extension of the file is .csv. Please let me know if the issue still persists

**Comment by JRWinWin** [comment]
Hey @akhilesh-94 , you are correct. My computer's Excel was changing the CSV encoding upon opening which changed the UTF-8 to a different setting.
