### ISSUE TITLE
Incorrect SPI Format in View History

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#376]
![SPI Format in View History](https://user-images.githubusercontent.com/48923883/60471718-c7ff7080-9c1a-11e9-917c-dcd1512b0348.png)

Issue: The format of SPI tags in View History is incorrect. The correct formatting is: **SPI - Access to exercise opportunities**. _There are no numerical digits present_. SPI and SDG differ in this way. 

Expected: Remove the numerical digits that are currently present in SPI records in View History

**Comment by akhilesh-94** [comment]
If your still seeing the numerical digits, they must be some old entries in the database. Please ignore that

**Comment by JRWinWin** [comment]
![Screen Shot 2019-07-03 at 10 22 57 AM](https://user-images.githubusercontent.com/48923883/60611995-8c7cb780-9d7c-11e9-99c7-f910e7170dbc.png)
@akhilesh-94 I just added these SPI tags and the numerical digits are still present.

**Comment by BethRR** [comment]
This is Pri 1 as this creates a credibility issue for WinWin when we display incorrect names for tags

**Comment by arvindkhatik012** [comment]
Hi Beth,

We have fixed the issue now for organization and program SPI tags View History.

Could you please check and confirm.

![view_history_fix_spi_tags](https://user-images.githubusercontent.com/45760420/61021365-dee25780-a3be-11e9-8fe1-00dc650fe206.png)

**Comment by JRWinWin** [comment]
This issue has been resolved. Thanks!
