### ISSUE TITLE
Resetting password with non-conforming password throws error and then logs user in/displays blank page

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#379]
Entering an invalid password (too short) when resetting a password causes the application to throw an error, then appear to log-in and display a blank screen and user can never log-out. Note: We should add password requirements to the screen and the email so users make valid passwords.

REPRO STEPS:
1) In login screen click forgot password
2) Enter verification code you receive in email and then enter a non-valid password like GoWin!
3) Note that you will get a momentary error message that says passand then be routed to a blank landing page
4) Also note that is impossible to log out or log in. 
5) If admin attempts to delete user and then re-add, they get message that user already exists.

EXPECTED: Would get an error that tells user their password in invalid, provides rules/requirements for an acceptable password and allows them to enter a better/valid password. Then allows them to log in with valid password.

ACTUAL: User gets error and no opportunity to correct their error and is thrown into a loop.

**Console displays the following:**
Failed to load resource: the server responded with a status of 400 ()
index.js:36 User session is already active, moving to landing page Object
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/organization?pageNo=0&pageSize=10:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/user:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/organization/ntee_data:1 Failed to load resource: the server responded with a status of 400 ()
react-dom.production.min.js:194 TypeError: e.data.map is not a function
    at industryClassificationSelector.js:28
    at index.js:70
    at index.js:30
    at index.js:84
    at index.js:30
    at Function.R [as mapToProps] (appliedOrgFiltersList.js:589)
    at r (wrapMapToProps.js:43)
    at u (selectorFactory.js:52)
    at c (selectorFactory.js:69)
    at selectorFactory.js:74
Qn @ react-dom.production.min.js:194
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/organization/spidata:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
industryClassificationSelector.js:28 Uncaught (in promise) TypeError: e.data.map is not a function
    at industryClassificationSelector.js:28
    at index.js:70
    at index.js:30
    at index.js:84
    at index.js:30
    at Function.R [as mapToProps] (appliedOrgFiltersList.js:589)
    at r (wrapMapToProps.js:43)
    at u (selectorFactory.js:52)
    at c (selectorFactory.js:69)
    at selectorFactory.js:74
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/organization/sdgdata:1 Failed to load resource: the server responded with a status of 400 ()
2api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
ec2-34-222-155-54.us-west-2.compute.amazonaws.com/organization/naics_data:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)

**Comment by akhilesh-94** [comment]
I am attaching this for reference from [slack](https://winwin2016.slack.com/archives/G8HRS371P/p1560938374136900)

**Comment by akhilesh-94** [comment]
Duplicate of #180

**Comment by BethRR** [comment]
@akhilesh-94  The error text needs to include requirements for valid password (for example: "Password must be at least 8 characters long and must contain at least one digit and at least one upper case and one lower case letter.")

**Comment by BethRR** [comment]
Confirmed fix --just realized you have put the requirements in the ? hover. Not completely discoverable, but can work for the MVP
