### ISSUE TITLE
50k upload attempt - FAILED, but with "Created Successfully" notification banner

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#422]
Issue: I attempted to upload a file with 50k records. It processed the request quickly, and I received a "Created Successfully" green banner message. Yet the records did not upload successfully, and there was not a notification sent to Slack. **The upload failed, and I received a Successful notification.**

Expected: Accurate status/outcome reporting for the bulk upload process. The user should never receive a "Created Successfully" message when the upload process has not been completed.

**Comment by JRWinWin** [comment]
I attempted the same upload today and it produced the same, unsuccessful results with the "Created Successfully" banner message

**Comment by arvindkhatik012** [comment]
@beth can you again try to upload the file as it was failed due to server restart because of new deployment.

You will be notified on slack once it is done

**Comment by beth** [comment]
@BethRR, think the above comment was meant for you!

**Comment by BethRR** [comment]
Thank you @arvindkhatik012. It looks like these rows were not actually written to the db. Maybe they were inserted in a db  other than winwindb-dev?
