### ISSUE TITLE
Org Mgmt | Selection Checkbox: Clicking on checkbox for one organization selects all organizations with the same name

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#424]
When user attempts to select an org for an action, any other org with same name is automatically selected as well and this cannot be avoided. Expected behavior: selecting checkbox for a single row selects ONLY that row.

**REPRO STEPS:**
1) Navigate to Organization Management: http://d3vudu8znrvs1z.cloudfront.net/organizations
2) In 'Organization Name' filter enter 'toastmasters' -- you should have a list of about 222 orgs from a variety cities, all with unique organization ids
3) Try to select one of the organizations ( user would do this to assign an high prio tag, for example). Note that by selecting one org, you have selected all with the same name. You can also repro this **without** filtering by org name, but it's easier to see this way.

Expected result: selecting checkbox for a single row selects ONLY that row.
Actual result: ALL rows with matching org name are selected despite being different orgs.

![OrgSelectionIssue](https://user-images.githubusercontent.com/49886260/60841123-e7038280-a185-11e9-8bd2-dd97c9be27dc.gif)

**Comment by JRWinWin** [comment]
This issue is resolved
