### ISSUE TITLE
Dataseeders permissions not functioning correctly and making it impossible to work in system

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#427]
When a Dataseeder logs in, all they get is a blank screen. Their only options appear to be log-in log out. This makes them utterly unable to work.

Dataseeders should have the same permissions as Administrators with the following EXCEPTIONS:
- Only admins can upload files
- Only admins can CRUD in user management

<img width="1680" alt="Blank screen" src="https://user-images.githubusercontent.com/49886260/60913198-bd0c9780-a23b-11e9-9f07-ff51d6de4ec5.png">

**Comment by akhilesh-94** [comment]
@BethRR Could you please check the role of the dataseeder user, if it is correctly set to the value **DataSeeder**

**Comment by BethRR** [comment]
Unable to test until my dataseeder account can log in (#453 ).

**Comment by BethRR** [comment]
Confirmed fix and closing
