### ISSUE TITLE
Filter Reset Issue

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#428]
Repro: 
1. Apply filter "Edited by User: John Raynolds". This reduces the Organization count from 35,616 to 8,019
2. Remove filter "Edited by User: John Raynolds". the Organization count returns to 35,616.
3. Search for any organization name, for instance "animals". The Organization count will change accordingly.
4. Delete search entry in the organization name search bar. Press enter to reset the Organization list. The Organization count resets to 8,019 even though the filter that produced that Organization count (filter "Edited by User: John Raynolds") was removed multiple steps ago. The user would be either confused by the lower number of Organizations or not be able to find many organizations.

Expected: The Organization list must be complete when there are no filters applied to it.

**Comment by akhilesh-94** [comment]
Hi @JRWinWin, I am not able to reproduce this issue. Could you please check again?

**Comment by JRWinWin** [comment]
I am also not able to repro this issue now. Must have been a caching issue. Consider this resolved.
