### ISSUE TITLE
Org Management Filter: 'Edited by' filter should be sorted alphabetically be user name

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#439]
Currently sorting order seems unorganized

**Comment by akhilesh-94** [comment]
@BethRR By default the table is sorted by organization's name. We can add the functionality for user to sort the column.

**Comment by BethRR** [comment]
@akhilesh-94 - the request is to sort the dropdown alphabetically for the 'Edited By' Filter See attached
![Filter](https://user-images.githubusercontent.com/49886260/61155085-db290080-a4a4-11e9-8fe3-d29607d221d9.png)

**Comment by arvindkhatik012** [comment]
we have resolved the issue now
![user_list_ascending](https://user-images.githubusercontent.com/45760420/61187051-8d6ded00-a68a-11e9-9cfd-4d7017b76657.jpg)

**Comment by BethRR** [comment]
Thank you @arvindkhatik012 . Confirmed fixed and closing.
