### ISSUE TITLE
Org Management: Edited by column displaying inconsistent values

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#440]
Sometimes this field appears to display created by value (maybe when it's been bulk uploaded?) hard to tell.  Then other times it displays nothing even though there is a value in the database.
Other times it does NOT show the name of the person who last edited, while other times it does. We have not been able to find a consistent behavior. Expected value is the name of the person who last edited the org.

**Some Repro Steps/Examples:**
1) Navigate to http://d3vudu8znrvs1z.cloudfront.net/organizations and filter for 'Edited by' John Raynolds. Note that in the first page of 10 results, only TWO of them have John listed in the Last Edited Column. Some are blank, some have other people's names. Looking closer at the items in this list:

  - For 37 cellars which has a blank in the Edited By column: If you open db and Select * from organization where id = 938620 , you'll see that John Raynolds acct is listed in the created by and edited by columns. The creation and edited timestamps are the same, so I'm assuming this is a bulk up load, but it's hard to tell.

- For Kitsap Legal Services which displays 'Sunny' in the Edited By column:  Look at http://d3vudu8znrvs1z.cloudfront.net/organizations/46383/view-history and note that John Raynolds and John has made all of the most recent edits to the org.  Likewise if you look in the db Select * from organization where id = 46383, you'll see john's account in the edited by field. It's unclear why Sunny's name is here (Sunny is the creator of this org in the db).

**Comment by arvindkhatik012** [comment]
Hi @BethRR ,

We had tried to reproduce the issue in dev with same organization id "46383" and found no issues i.e. Last Edited By is working fine.

**Comment by BethRR** [comment]
@arvindkhatik012 - I think one issue is that organization table and the org_history table are storing different  fields in the updated info (one stores the name and one stores the email). It would be better to make these consistent and match the filter dropdown.

**Comment by arvindkhatik012** [comment]
Hi @BethRR

**Comment by BethRR** [comment]
Closed as fixed
