### ISSUE TITLE
Inactive users should not be able to access the Admin Console

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#451]
Issue: After users have been inactivated, they can still access the Admin Console. The permissions and log-in capabilities are unchanged when a user's activity status has changed.

Expected: Inactive users should not be able to log in to the Admin Console.

**Comment by arvindkhatik012** [comment]
Hi @BethRR ,
We have fixed the issue now so from now when a admin mark the user as inactive from winwinwiki ,user status will be disabled from cognito and it's AWS Status will be changed to FORCE_CHANGE_PASSWORD from CONFIRMED and when the admin mark the user as active ,the user will be enabled in cognito and the user can now able to login by using previously used password and after the successful login the user AWS Status will be changed to CONFIRMED from FORCE_CHANGE_PASSWORD

**Comment by JRWinWin** [comment]
This issue has been resolved
