### ISSUE TITLE
"Please send valid payload" error when attempting to change password

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#453]
When attempting to change my password I received the following error -- what does it mean?  If this is a legitimate error, we need to give the user more helpful steps.

REPRO STEPS:
1) Navigate to http://d3vudu8znrvs1z.cloudfront.net and attempt to login with these credentials:
beth.r.roberts@gmail.com | P@ssw0rd123. Note the error message that says you need to reset password.
2) Navigate to http://d3vudu8znrvs1z.cloudfront.net/reset-password ( it would be nice if user was given a link) and attempt to change password with this verification code : 257683 Now you should see the payload error described in this bug

**CONSOLE ERRORS:**
4ec2-34-222-155-54.us-west-2.compute.amazonaws.com/user/confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()

[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"userPassword" type=​"password" aria-describedby=​"passwordDesc" placeholder=​"Confirm Password" class=​"form-control" name=​"confirmPassword" value=​"P@ssw0rd123">​

![PayloadError](https://user-images.githubusercontent.com/49886260/61251967-e1231980-a710-11e9-9fa6-96ba051f6406.png)

**Comment by akhilesh-94** [comment]
@BethRR I am not able to reproduce this issue. Could you please check again?

**Comment by BethRR** [comment]
@akhilesh-94  - I'm still seeing this. I've added repro steps to the description.

**Comment by akhilesh-94** [comment]
Hi @BethRR, Please don't jump onto the reset-password page, that won't work hence the error message is justified. The workflow is 
1. Click on forgot password link, where you need to enter your email-address(this is required), which sends a confirmation code. 
2. On the reset password page, now that you have entered e-mail address from step 1, you have a valid payload now.
So, the source of error was : payload was missing e-mail address.

**Comment by BethRR** [comment]
fixed
