### ISSUE TITLE
http://dev.winwin.care/reset-password does not render correct page

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#462]
Something is stripping off the '/reset-password portion' of the URL when you type or paste the URL into the browser and you can never get to the password reset screen. Interesting to note that when you are redirected to this page via the 'forgot password' screen the page renders fine.

**REPRO STEPS**
Navigate to http://dev.winwin.care/reset-password (as a user might who needs to reset password ). Note that something is stripping off the /reset-password portion of the URL and you can never get to the password reset screen.

![reset_render](https://user-images.githubusercontent.com/49886260/61388048-1c862b00-a86c-11e9-8dca-b76af4918ad0.gif)

**Comment by akhilesh-94** [comment]
@BethRR Please don't jump directly to reset password page, that won't work. Click on forget password first on login page
 https://github.com/winwinwiki/winwin-frontend/issues/453#issuecomment-512153915

**Comment by arvindkhatik012** [comment]
@BethRR We have disabled the direct navigation to all the user management api due to security issues.
so from now you have to follow the correct flow for forgot password.

**Comment by BethRR** [comment]
confirmed fix
