### ISSUE TITLE
Errors when attempting to reset password

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#463]
When attempting to reset password, I am getting the following error now. I think we previously had a similar issue -- maybe some old code has creeped in?

**REPRO STEPS**
1) Navigate to http://dev.winwin.care/reset-password (tough to do...see related bug #462)
2) Enter verification code 487711 (this is for beth.r.roberts@gmail.com)
3) Enter new passwords and then hit reset. Note that nothing happens.

**CONSOLE ERRORS:**
env= production
reset-password:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"userName" type=​"password" aria-describedby=​"userNameDesc" placeholder=​"Password" class=​"form-control" name=​"password" value=​"P@ssw0rd123">​
reset-password:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input id=​"userPassword" type=​"password" aria-describedby=​"passwordDesc" placeholder=​"Confirm Password" class=​"form-control" name=​"confirmPassword" value=​"P@ssw0rd123">​
confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
m @ api.js:14
Promise.then (async)
m @ api.js:15
Promise.then (async)
(anonymous) @ api.js:50
r @ api.js:9
(anonymous) @ resetPasswordAction.js:12
(anonymous) @ index.js:8
(anonymous) @ redux.js:449
i.onSubmit @ index.js:210
i @ react-dom.production.min.js:14
a @ react-dom.production.min.js:15
s @ react-dom.production.min.js:15
l @ react-dom.production.min.js:17
p @ react-dom.production.min.js:18
d @ react-dom.production.min.js:18
g @ react-dom.production.min.js:21
De @ react-dom.production.min.js:84
Lr @ react-dom.production.min.js:249
W @ react-dom.production.min.js:39
Ue @ react-dom.production.min.js:86
Ur @ react-dom.production.min.js:250
Fe @ react-dom.production.min.js:85
confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
m @ api.js:14
Promise.then (async)
m @ api.js:15
Promise.then (async)
(anonymous) @ api.js:50
r @ api.js:9
(anonymous) @ resetPasswordAction.js:12
(anonymous) @ index.js:8
(anonymous) @ redux.js:449
i.onSubmit @ index.js:210
i @ react-dom.production.min.js:14
a @ react-dom.production.min.js:15
s @ react-dom.production.min.js:15
l @ react-dom.production.min.js:17
p @ react-dom.production.min.js:18
d @ react-dom.production.min.js:18
g @ react-dom.production.min.js:21
De @ react-dom.production.min.js:84
Lr @ react-dom.production.min.js:249
W @ react-dom.production.min.js:39
Ue @ react-dom.production.min.js:86
Ur @ react-dom.production.min.js:250
Fe @ react-dom.production.min.js:85
confirmResetPassword:1 Failed to load resource: the server responded with a status of 400 ()
api.js:14 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at m (api.js:14)
m @ api.js:14
Promise.then (async)
m @ api.js:15
Promise.then (async)
(anonymous) @ api.js:50
r @ api.js:9
(anonymous) @ resetPasswordAction.js:12
(anonymous) @ index.js:8
(anonymous) @ redux.js:449
i.onSubmit @ index.js:210
i @ react-dom.production.min.js:14
a @ react-dom.production.min.js:15
s @ react-dom.production.min.js:15
l @ react-dom.production.min.js:17
p @ react-dom.production.min.js:18
d @ react-dom.production.min.js:18
g @ react-dom.production.min.js:21
De @ react-dom.production.min.js:84
Lr @ react-dom.production.min.js:249
W @ react-dom.production.min.js:39
Ue @ react-dom.production.min.js:86
Ur @ react-dom.production.min.js:250
Fe @ react-dom.production.min.js:85

**Comment by akhilesh-94** [comment]
@BethRR Did you jump directly to reset password page?

**Comment by arvindkhatik012** [comment]
@BethRR Don't jump directly onto reset password page as first you need to put your email address by clicking the forgot password link than after that you will again get an verification code on email than type that verification code along with the password.

**Comment by BethRR** [comment]
confirmed fixed -- closing.
