### ISSUE TITLE
Bulk Upload File Template Download Error

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#476]
Repro: 
1. While signed in as an Admin, navigate to the Bulk data upload page
2. Click "Download Template"

Issue: 
![Screen Shot 2019-07-18 at 2 48 08 PM](https://user-images.githubusercontent.com/48923883/61495490-02347600-a96e-11e9-9a60-8098fe44095b.png)

Expected: Admins need to be able to download the Bulk Upload template.

**Comment by arvindkhatik012** [comment]
The issue was happned due the file was mitakenly marked as private from public in S3 bucket "winwin-public-bucket-dev".

we have resolved the issue now.
