### ISSUE TITLE
SPI/SDG Tagging via Bulk Upload Process

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#480]
Issue: After the successful bulk upload, I was doing a quality check on the outcome. The focus of the check was to ensure proper autotagging of SPI/SDGs for organizations by NAICS codes. The quality check yielded inconsistent results. The autotagging process works properly when there is only one SPI and/or SDG tag assigned to a NAICS code. The autotagging process does not work when there is more than one SPI and/or SDG assigned to a NAICS code. When there is more than one SPI and/or SDG assigned to a NAICS code, the result is that no tagging occurs. 

Expected: The autotagging process must work for all NAICS and NTEE codes with all numbers of SPI/SDG tags assigned to them. The process must convey all SPI/SDG tags that are assigned to the NAICS codes.

**Comment by arvindkhatik012** [comment]
we have fixed the issue now. we have uploaded the organization with Id as 1930086 and it worked fine.
Please check below for your reference.

http://dev.winwin.care/organizations/1930086/spi-tags
http://dev.winwin.care/organizations/1930086/sdg-tags

**Comment by JRWinWin** [comment]
This issue has been resolved
