### ISSUE TITLE
Organization Management Page: Location search should have typeahead combobox

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#481]
The inability to filter the location is a big usability issue for the Organization Management page. This is a PRi 1 issue because there are a few search scenarios that are not at all possible.Using typeahead in a combo box  would help get the user to the info they want without taking the time to build a robust filtering ui (long term that seems like the right route and would give the user more powerful options).

Some examples of Pri 1 Scenarios:
1) Limit search to organizations in Washington state
2) Disambiguate common names like Washington, Springfield, Adams, or Franklin to find the correct location for the search

In a perfect world, the control would work as well as this one in linked-in jobs https://www.linkedin.com/jobs/

**Comment by sunnytambi** [comment]
Hi @BethRR , current implementation is as per original design.
I understand it may become even more useful if we make some changes to it, however at this moment, we should look at the closure of MVP. We can take all these enhancements post mvp as well.

We need to positively commit to a date for MVP.

**Comment by BethRR** [comment]
@sunnytambi - this was in my notes to talk to you about last night and is critical. Our big problem with not having this is that we cannot find organizations in Washington state for example -- this is a critical part of the workflow. It seemed to me that this is easier that creating a complex set of filters, which is what I discussed with @arvindkhatik012 and @akhilesh-94 when we met last week.  The current search is not helpful in directing the dataseeders to the right set of ogranizations -- this is an important 'must have' workflow that needs to be addressed one way or another -- whether by filtering or by using a typeahead.

**Comment by BethRR** [comment]
The search was replaced with a dropdown that works for now. Typeahead should be investigated post MVP
