### ISSUE TITLE
Address critical vulnerabilities outlined by Github, as needed

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#482]
Please review and address Hi Severity issues that apply: https://github.com/winwinwiki/winwin-frontend/network/alerts

**Comment by arvindkhatik012** [comment]
The link is not accessible

**Comment by BethRR** [comment]
@arvindkhatik012 - removing fixed label since it seems like the issue is that my link did't work for you. You should be able to see the issues on the Github page and click through links there is my link isn't working for you ( see screenshot). Navigate to https://github.com/winwinwiki/winwin-frontend 
![Security](https://user-images.githubusercontent.com/49886260/61666871-636d8980-ac8d-11e9-8ec1-e8829d00742d.png)

**Comment by sunnytambi** [comment]
Hi @BethRR , these issues are coming into generated "package-lock.json" file which are mostly false positive and can be ignored as we use its corresponding source file "package.json" to install dependency libraries.
Please check this post for details -- https://dev.to/pi0/why-i-dislike-github-security-alerts-and-how-to-disable-them-1cg2

Over an above this, when we make a change in dependency as suggested in the alert, it breaks the whole dependency-cycle and the project stops building.

I am currently resolving this as "deferred".
