### ISSUE TITLE
Organization: Population served should be a char 255 field (currently set as an integer)

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#485]
'Population served' can not be an integer (the database field definition needs to be changed to char 255) -- it will always be descriptive text (e.g., low-income families, etc.). This is critical for quality data entry.

Longer term we'll need to make it function more similar to 'Regions Served' -- but that is post MVP for now.

**Comment by arvindkhatik012** [comment]
we have changed the schema with new definition

**Comment by JRWinWin** [comment]
This issue has been resolved
