### ISSUE TITLE
Org Management Search: Clear search button needed

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#495]
From user testing -- there is currently no intuitive way to clear a search. Users tend to get confused when confronted with a search not clearing. A couple possible UI approaches attached.

**REPRO STEPS (taken directly from user testing)**:
1) navigate to http://d3vudu8znrvs1z.cloudfront.net/organizations
2) enter 'Farestart' into the search box and hit enter. Note that you have zero results.
3) remove 'Farestart' text from search box -- note that nothing changes.
4) Open the filter dialog and click 'Reset filters'. Note that number of organizations returns to the full set 346,796 
5) Type 'Farestart' into organization filter -- notice that no matching organization is found because the previous search/search results have not actually been cleared. Note that there s NO way to clear the Search other than refreshing the page.
6) Refresh page and enter 'Farestart' into the organization filter - note that you will get a single Farestart result.

**Expected:** user can clear their search
**Observed:** User has no way to clear their search unless they refresh the entire page -- which is not intuitive and not how most applications or websites work.

**Comment by akhilesh-94** [comment]
@BethRR As of now, we need to press enter key to reset the search results

**Comment by BethRR** [comment]
This seems to have been fixed perhaps by the other search fixes.
