### ISSUE TITLE
Organization Delete Function Hanging

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#507]
Repro: 1. On Organization Management, attempt to delete an organization.
2. Click "Delete Organization" on the Alert pop up.
3. You will receive a "Deleted Successfully" green banner, but the page will be stuck in the processing page view. 
4. The organization will actually be deleted, but the user gets stuck on the page. 
![Organization Delete Hang Up](https://user-images.githubusercontent.com/48923883/61972534-ac2b8800-af96-11e9-8f03-06566b106599.png)

Expected: The delete function must return to the Org Management page in a normal fashion once the deletion process is complete.

**Comment by akhilesh-94** [comment]
@JRWinWin I am not able to reproduce this issue

**Comment by JRWinWin** [comment]
This issue is resolved
