### ISSUE TITLE
Organization Basic Information - Disable NTEE when Sector Chosen as Private

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#508]
Expected: While editing Basic Information for an organization, if a user selects Sector as **Private**, the NTEE field will become greyed out. 

Explanation: NTEE is a classification system for only the Social and Public Sectors, therefore it should never apply to a Private Sector organization.

**Comment by JRWinWin** [comment]
![NTEE grey out while Private Sector](https://user-images.githubusercontent.com/48923883/61974088-8c965e80-af9a-11e9-8802-4fb36227fd06.png)

**Comment by akhilesh-94** [comment]
@JRWinWin Not able to reproduce

**Comment by JRWinWin** [comment]
@akhilesh-94 There is nothing to reproduce here. To clarify, this a request for a change to the properties of the NTEE field. 

Current: When a user selects Sector > Private, they are still able to enter an NTEE value. 
Expected: When a user selects Sector > Private, they should not be able to enter an NTEE value. The NTEE data field should be greyed out in similar manner to the conditional Sector Level and Sector Level Name grey out function.

**Comment by akhilesh-94** [comment]
@JRWinWin  This is a feature request, please don't log this is as an issue here.

**Comment by JRWinWin** [comment]
This issue has been resolved
