### ISSUE TITLE
Organization - Data Set Creation produces Error

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#509]
Repro: 1. Navigate to Data Sets within an organization.
2. Select "Add New Data Set" and fill fields accordingly with a Data Set Name that is completely new.  
3. Select "Save". An error message will appear and the data set will not be created. 
4. If the data set already exists in the database, the data set will be created successfully.

Expected: Data set creation should be operable under any circumstance including when the user is entering a new Data Set Name. 

![Data set Failure](https://user-images.githubusercontent.com/48923883/61973812-d6cb1000-af99-11e9-8c68-2ef242a49079.png)

**Comment by arvindkhatik012** [comment]
we have fixed the issue now.

**Comment by JRWinWin** [comment]
This issue has been resolved
