### ISSUE TITLE
Resources/Data Sets - Change "Add New [X]" name

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#513]
Expected: This issue applies to both Resources and Data Sets. The "Add New Data Set" button should be changed to "Add Data Set". So remove the "New" from the Button label. The new buttons should be labeled "Add Data Set" and "Add Resource" respectively. 
![Change Add new resource title](https://user-images.githubusercontent.com/48923883/61976317-5c5

![Change Add NEw Data Set name](https://user-images.githubusercontent.com/48923883/61976319-5eb41880-afa0-11e9-89ba-98dcf5eb4407.png)
1be80-afa0-11e9-88f8-86d326cd2c17.png)

**Comment by nandhae** [comment]
I can pick this up.

**Comment by JRWinWin** [comment]
This issues is partially resolved. 
"Add New Data Set" has been changed to "Add Data Set". 
But "Add New Resource" has **not** been changed to "Add Resource".

**Comment by JRWinWin** [comment]
We want "Add New Resource" to be changed to "Add Resource". This issue is not fixed until that change has been made.
