### ISSUE TITLE
Note - "Add Another" title change

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#514]
Expected: On the Notes page, the addition button is titled "Add Another". The addition button should be re-titled "Add Note". 
![Notes - Add Another to Add Note](https://user-images.githubusercontent.com/48923883/61976601-0c272c00-afa1-11e9-8656-b0c2c764bd3d.png)

**Comment by nandhae** [comment]
I'm picking this up.

**Comment by JRWinWin** [comment]
This issue is resolved
