### ISSUE TITLE
Organization Chart - Click and Drag Ability 

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#516]
Issue: In Org Chart, we used to be able to click and drag Child organizations to move them within an organization. We valued this feature. This feature is now disabled and we cannot rearrange the Org Chart as we want to. 

Expected: Restore the click and drag feature within Org Chart, so we can rearrange Child Organizations within the feature.

**Comment by akhilesh-94** [comment]
@JRWinWin You can drag them around, but saving the rearranged org chart won't be possible to implement for now. So, we decided to remove that feature for now
