### ISSUE TITLE
Organization Management - Add "Created By" Filter to Filter Management // Enable "Created By" and "Edited By"

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#520]
Expected: Created By is one of 6 columns in the Organization Management table. That placement makes it a very important field and such should be able to filtered. We currently do not have a filter that acts on that field. 
We have established precedent by having an "Edited By" filter, and we must have a "Created By" filter. The placement of this filter will be above the "Edited By" filter in the Filter Management box and function in a similar manner.

**Comment by JRWinWin** [comment]
Issue: The "Created By" and "Edited By" are currently **not** functioning in the staging environment. 
Expected: "Created By" should be a functioning filter acting upon the Created By column. "Edited By" should be a functioning filter acting upon the Edited By column.

**Comment by arvindkhatik012** [comment]
we have fixed the issue.
