### ISSUE TITLE
Kibana Index: Admin url empty for ~40% of organizations in the index when ALL should have admin URL values

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#568]
ALL organizations should have admin URL values in the Kibana index, but for some reason only ~40% of organizations in the index actually have admin URL values. I couldn't discern any patterns.

Repro steps

1) Navigate to https://search-winwindev-3bunivyjknlg772kykxnenk4qi.us-west-2.es.amazonaws.com/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(adminUrl,name,parentOrganizationName),index:'3c3c71b0-b448-11e9-b1d4-4bccfe0423b1',interval:auto,query:(language:kuery,query:''),sort:!(_score,desc))

2) Note the empty admin URLS

**Comment by arvindkhatik012** [comment]
@BethRR This should not be an bug as I have updated only selected organizations for you to test the kibana url. (i.e. org Id = 20 , OrgId = 37353 and it's children organizations ) anyway now I am updating the admin url for all the available organizations in kibana. Hence Marking the bug as fixed and invalid
