### ISSUE TITLE
Google Places API Interaction with Google Chrome Browser?

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#57]
![Autocomplete Pickup](https://user-images.githubusercontent.com/48923883/55656599-6ca11c00-57ac-11e9-9e06-7baabd741d62.png)

**Comment by akhilesh-94** [comment]
No, the autocomplete being shown is related to the browser only.

**Comment by JRWinWin** [comment]
Great, thanks
