### ISSUE TITLE
Regions Served Free Writing / Google Places API Limitation

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#59]
![Region Served Free Writing](https://user-images.githubusercontent.com/48923883/55656858-4c259180-57ad-11e9-96f0-42c8b0703f39.png)

**Comment by JRWinWin** [comment]
Another example of an entry that must be acceptable in Region Served
![King County Regions Served](https://user-images.githubusercontent.com/48923883/55656946-9c9cef00-57ad-11e9-8f24-46cd253e1f22.png)

**Comment by akhilesh-94** [comment]
@JRWinWin If the entry does not show up in the suggestions should we consider it as a valid region?

**Comment by arvindkhatik012** [comment]
@JRWinWin We acknowledge that the region served needs to be a free text but for the regions served map being shown in kibana we need a valid region (which could make it difficult for us to process the free text as a valid region).

**Comment by akhilesh-94** [comment]
@JRWinWin we would be needing a master list of regions-served. As of now, we have added a master list of our own.

**Comment by BethRR** [comment]
The control is not displaying suggestions on Regions served. John has delivered a list. Will log an issue to resolve this.
