### ISSUE TITLE
Program Resources Crash Site

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#60]
![Program Resource Crash](https://user-images.githubusercontent.com/48923883/55659211-87c45980-57b5-11e9-8a7d-23cc8c4fda5c.png)

**Comment by akhilesh-94** [comment]
@JRWinWin there is a restriction on the 'Count' field. It needs to be an Integer only field

![image](https://user-images.githubusercontent.com/43365228/55784551-6ffb1700-5ace-11e9-87ff-affce9186466.png)

**Comment by JRWinWin** [comment]
The issue at the time was trying to add any resource would make the website fail. It appears to be working now.
