### ISSUE TITLE
Org chart doesnt load first time

### ISSUE THREAD

**Issue by sunnytambi** [winwinwiki/winwin-frontend#637]

**Comment by BethRR** [comment]
It also appears to look for the naics and ntee codes, which doesn't seem relevant for org charts.

**Comment by sunnytambi** [comment]
NAICS and NTEE codes are loaded on the "Basic Details" page to populate the respective dropdowns.
They aren't loaded on org chart page.
The org chart page is slow as the db operation is complex and bulky.
Closing this issue for now.
