### ISSUE TITLE
Unable to edit parts of created Children Organizations

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#638]
Repro: 1. Navigate to JOHN'S TEST ORG - PLZ DELETE AT SOME POINT (organization).
2. Navigate to one of the child organizations and attempt to update organizational information in a proper fashion. 
3. After updating the information, go to Organization Chart and navigate back to the parent organization. 
4. Navigate to the child organization in which the changes were made. Some of the changes will not be saved. Any changes made to Basic Information, Data Sets, and Resources will not be saved. 

Issue: Users cannot enter data, or make changes to child organizations. 

Expected: Users must be able to enter data and make changes to Basic Information, Data Sets, and Resources in child organizations.

**Comment by sunnytambi** [comment]
Hi @arvindkhatik012 , I check this and found that even after successfully creating resource / data set, the backend returns empty list on page refresh .. Check this out in backend.

**Comment by arvindkhatik012** [comment]
we have fixed the issue

**Comment by BethRR** [comment]
Verified fix. Closing as fixed.
