### ISSUE TITLE
Organization Management - "Clear All Filters" doesn't wipe the Org Search entry

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#648]
Repro: 1. In Organization Management, enter a search term into the Organization Name field.
2. Hit the "Clear All Filters" button. The Organization Name search will be functionally cleared, but the field in the UI does not clear the search entry.

Expected: "Clear All Filters" should functionally clear the search AND clear the search entry from Organization Name. Users could be confused by the search title remaining in the search field after the "Clear all Filters" button has been selected.

**Comment by sunnytambi** [comment]
Done. Please check.

**Comment by JRWinWin** [comment]
This issue is still present

**Comment by sunnytambi** [comment]
Please check now.

**Comment by JRWinWin** [comment]
This issue is still present

**Comment by sunnytambi** [comment]
Promoted fixes to staging too.. please check on staging now ..
