### ISSUE TITLE
Kibana/Elastic: Index needs to be structured so that all info is accessible to Saved Searches in Discover and Dashboard

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#656]
Currently the program information is not accessible in Discover ( where we can create saved searches). We have observed that data table visualizations are less performant and would like to use saved searches as we did in the previous Kibana dashboards.  Thus we need the  index to be structured to support those saved searches.

**Comment by arvindkhatik012** [comment]
As discussed the index structure is in good shape. Please let us know if any changes required.

**Comment by BethRR** [comment]
This issue is ongoing and can only be addressed with a restructuring of the Elastic Index -- which has not yet been done.

**Comment by BethRR** [comment]
Added blocked label to flag that these are blocked until new index or indices created
