### ISSUE TITLE
Kibana: Data tables not handling one to many and exploding size due to resources and datasets

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#657]
In old Kibana we could produce a table where each org or program was a single row with many datasets and resources (see attached screenshot for example of what I mean.) 
![OldKibana](https://user-images.githubusercontent.com/49886260/63893016-ef19ba80-c99d-11e9-8366-862c6c4cde6c.png)

We've tried, but haven't been able to do this with the new data/Kibana. Two key issues arise:
1) The wrong program descriptions are displayed in inconsistent way (3 different program descriptions displayed for a single program). 
2) Table is expanded tremendously due to having multiple rows (e.g., 1 for each dataset and 1 for resource associated with a program)

Here is what we get :
https://search-winwin-stage-kx4nf3pxtyy2t5ehq7q6vkbe3m.us-west-2.es.amazonaws.com/_plugin/kibana/app/kibana#/visualize/edit/6d199d10-c9cb-11e9-b2e9-b968385da09b?_g=()&_a=(filters:!(),linked:!f,query:(language:lucene,query:''),uiState:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:name.keyword,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:_key,otherBucket:!f,otherBucketLabel:Other,size:50000),schema:bucket,type:terms),(enabled:!t,id:'3',params:(field:programs.name.keyword,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:_key,otherBucket:!f,otherBucketLabel:Other,size:50000),schema:bucket,type:terms),(enabled:!t,id:'4',params:(field:programs.description.keyword,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:_key,otherBucket:!f,otherBucketLabel:Other,size:50000),schema:bucket,type:terms),(enabled:!t,id:'5',params:(field:assets,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:50000),schema:bucket,type:terms),(enabled:!t,id:'6',params:(field:revenue,missingBucket:!f,missingBucketLabel:Missing,order:asc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:50000),schema:bucket,type:terms)),params:(perPage:10,showMetricsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,sort:(columnIndex:!n,direction:!n),totalFunc:sum),title:'Program%20Table',type:table))

Maybe the data need to be restructured? Or is there another way to address this?

**Comment by sunnytambi** [comment]
Hi @BethRR , @JRWinWin  ..as we discussed in one of our daily standup, we have broken individual dataset as a separate record so that you can do forward and reverse lookup i.e. from org to dataset and from dataset to org lookups.

We are not planning to make any changes to this. If you have some other use case which gets blocked due to our implementation.

**Comment by sunnytambi** [comment]
Hi @BethRR , @JRWinWin .. It can be done using Kibana visualization .. 
I created one for datasets. Here is the screenshot for the same ..

![image](https://user-images.githubusercontent.com/712304/64764148-1efcbc80-d55f-11e9-9849-52d763d9f3c2.png)

Please refer to this dashboard (scroll to bottom of it) - https://search-winwin-stage-kx4nf3pxtyy2t5ehq7q6vkbe3m.us-west-2.es.amazonaws.com/_plugin/kibana/app/kibana#/dashboard/f5b806c0-d330-11e9-acb5-e380a6d26908

**Comment by arvindkhatik012** [comment]
As discussed the index structure is in good shape. Please let us know if any changes required.

**Comment by BethRR** [comment]
As discussed with everyone, this issue is ongoing and can only be addressed with a restructuring of the Elastic Index -- which has not yet been done.

**Comment by BethRR** [comment]
Added blocked label to flag that these are blocked until new index or indices created
