### ISSUE TITLE
Migration Issue: Duplicate spi indicators assigned to organizations need to be removed

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#658]
Some orgs have duplicate indicators that need to be removed. These may be coming from the csv's or could this be related to the autotagging? If these are in the CSV, please remove or if this is an autotagging issue, please address.

![DupeIndicator](https://user-images.githubusercontent.com/49886260/64046261-5495b480-cb20-11e9-88b4-7e787fcc51f3.png)

**To see affected orgs and ids:**
SELECT 
    organization_id, 
    spi_id, 
    COUNT(*) occurrences
FROM org_spi_mapping
GROUP BY
    organization_id, 
    spi_id
HAVING 
    COUNT(*) > 1;

**Comment by arvindkhatik012** [comment]
We have updated the staging DB with the latest changes provided by @JRWinWin .

**Comment by BethRR** [comment]
@arvindkhatik012 Please update stage with files sent via slack on Sept 27 -- this should resolved the spi dupes in Organizations and Programs. Thank you!

**Comment by arvindkhatik012** [comment]
We have updated the staging DB with the migration files sent on 27 Sept.
