### ISSUE TITLE
Organization Management - Action Selection Box

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#66]
![Action bar](https://user-images.githubusercontent.com/48923883/55747435-153fbd80-59f1-11e9-9396-543884d3ebde.png)

**Comment by akhilesh-94** [comment]
@JRWinWin Yes, the actions can be applied to a selected org(s). So, the selected orgs will be set as the selected priority

**Comment by JRWinWin** [comment]
Nothing really happens when I try to mark any of those organizations with Action labels

**Comment by BethRR** [comment]
Setting priority works, but mark for tagging is not functioning.
