### ISSUE TITLE
View History - Incorrect View History Entry

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#662]
<img width="1205" alt="Incorrect View History Entry" src="https://user-images.githubusercontent.com/48923883/64201254-190e2980-ce43-11e9-9f65-5bbcb37bfc00.png">

Issue: I created "TEST ORAGNIZATION #1!" a few minutes ago for the purpose of testing the View History function. After making a few changes, I checked the View History and was surprised to see an entry that was made 6 days ago, or before the organization had even been created. 

Expected: Entries in an organization's View History should only pertain to actions made in regards to that Organization. Entries should not exist before the organization has been created.

**Comment by sunnytambi** [comment]
@JRWinWin  Somehow i tested it however not reproducing even after multiple attempts .. 
Do you have better steps to repro it?

**Comment by JRWinWin** [comment]
@sunnytambi I do not have better steps to repro it because I do not know how it happened. I have been unable to repro it as well. 
My concern is false view history data being pulled into Organization's View History. I was surprised to see that View History entry because its presence makes no sense. I do not believe user actions in the UI are what caused this issue.

**Comment by sunnytambi** [comment]
@JRWinWin  I am deferring it for now. If it reappear to you, please reopen with reproducible steps.

**Comment by BethRR** [comment]
Our guess is that this may be an artifact of a migration.
