### ISSUE TITLE
User Roles - Data Seeders must be able to Edit Basic Info and Org Chart

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#665]
Issue: Data Seeders are currently unable to edit an Organization's Basic Info and Org Chart. 
Expected: Data Seeders must be able to edit an Organization's Basic Info and Org Chart.

**Comment by sunnytambi** [comment]
Fixed . Please check.

**Comment by JRWinWin** [comment]
This issue is still present

**Comment by sunnytambi** [comment]
Please check now.

**Comment by JRWinWin** [comment]
This issue is still present

**Comment by sunnytambi** [comment]
Please check on staging now.
