### ISSUE TITLE
Data Sets - Hitting "Enter" on dataset dropdown deletes previous work

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#670]
In Staging
Repro: 1. Navigate to a program within an organization.
2. Add a data set with any name.
3. Add another data set, but name the data set with "Program" and down key to a data set name. Once on a data set name, hit the Enter button to select the name. The page will refresh and there will be no datasets present. 

Issue: Hitting enter, while choosing a data set name from the dropdown list, refreshes the page and deletes any previously created data sets on that page. 

Expected: Users must be able to use the Enter button to select a data set name from the dropdown list as this is a standard function. The Enter button must not delete previously added data sets.

**Comment by sunnytambi** [comment]
Fixed, please check now.

**Comment by BethRR** [comment]
Verified fix -- closing as fixed.
