### ISSUE TITLE
Kibana Auhtorization - Reader Role Access to Kibana fails

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#671]
Issue: In Staging as a Reader, I attempted to log on and got this message: 
![Screen Shot 2019-09-12 at 8 56 06 AM](https://user-images.githubusercontent.com/48923883/64801462-6eca8c00-d53d-11e9-8c6f-70064d8e1ba0.png)

On second attempt, I got this message: 
![Screen Shot 2019-09-12 at 8 56 42 AM](https://user-images.githubusercontent.com/48923883/64801491-7853f400-d53d-11e9-991a-3ac4b63501d9.png)

**Comment by sunnytambi** [comment]
Removed Kibana dashboard for Reader user and instead placed a static text to let user go to Wiki page.

![image](https://user-images.githubusercontent.com/712304/65227845-ffc5d800-dae6-11e9-8b70-21f1cbc9e8e0.png)
