### ISSUE TITLE
Org Mgmt: Clear filters button appears when no filters are active

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#675]
Steps to Repro:
1. In Org Management, click on Org Search box and search on books. Note results.
2, Clear text in Org Search box and hit enter -- this action is depended upon to clear the filter and return the full organization list.  Note that the"Clear All Filters" button appears after you hit enter.

Expected: There are no filters applied to this list in this instance, so the button should not appear.
Actual: Clear filters button appears when no filters are active

(this bug was initially logged in trello: https://trello.com/c/vLBlurZw
![ClearFiltersIssue](https://user-images.githubusercontent.com/49886260/65590919-70824f80-df40-11e9-90e2-5381ef1e2302.jpg)

**Comment by arvindkhatik012** [comment]
@BethRR We have fixed the issue
