### ISSUE TITLE
Org Mgmt: Org names column should be aligned left, but currently appears to be centered

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#676]
All other columns should continue to be centered  **except** for the Org Names column which should aligned left.

(was previously logged and unresolved in Trello: https://trello.com/c/uYFSvQZ3)

**Comment by sunnytambi** [comment]
Fixed and available on stage.

**Comment by BethRR** [comment]
Confirmed fix and closing as fixed
