### ISSUE TITLE
Add a 'Sign-up' Link to the Kibana page so Readers can request permission to access the dashboard

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#679]

**Comment by arvindkhatik012** [comment]
we have added signup link for kibana users.
![signup_kibana](https://user-images.githubusercontent.com/45760420/66098464-4a078880-e5c0-11e9-8826-c23b403c5701.JPG)

**Comment by BethRR** [comment]
Confirmed fix
