### ISSUE TITLE
Kibana: Admin URL should be clickable

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#684]

**Comment by arvindkhatik012** [comment]
We have Changed the type of AdminUrl From string to Url

![adminURl_link2](https://user-images.githubusercontent.com/45760420/66813120-d2d3dc00-ef51-11e9-81bb-d7d1f02e1687.PNG)
![adminURl_link1](https://user-images.githubusercontent.com/45760420/66813122-d2d3dc00-ef51-11e9-9782-84c50db97555.PNG)
