### ISSUE TITLE
Kibana Index includes ids/orgs that do not exist in the database

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#687]
The Kibana index contains organizations that are not in the database, even though index was updated after wiping/re-migrating the data and then publishing to Kibana via the UI. 

**Environments:** 
Kibana: wiki-stage.winwin.care 
Wiki Console DB: Winwindb-staging

**Below are the organizations that appear in Kibana index only:**
ID:100001
businessModel: - contactInfo: - createdAt:1,570,041,984,935 updatedAt:1,570,041,984,935 createdBy:Beth Roberts updatedBy:Beth Roberts createdByEmail:beth.roberts@winwin.care updatedByEmail:beth.roberts@winwin.care ein: - facebookUrl: - instagramUrl: - isActive:true linkedinUrl: - missionStatement: - naics_code: - name:BethTestHHS description: - ntee_code: - populationServed: - priority:Normal purpose: - assets: - revenue: - sector: - sectorLevel: - sectorLevelName: - selfInterest: - tagStatus: - twitterUrl: - type: - values: - websiteUrl: - adminUrl:https://stage.winwin.care/organizations/100001 parentId:4,579 rootParentId:4,495 parentName:Administration for Children & Families rootParentName:Health and Human Services (HHS) address.id:4,762 address.city: - address.country: address.county: - address.isActive:true address.state: - address.street: - address.zip: - address.createdAt:1,570,041,984,935 address.updatedAt:1,570,041,984,935 address.createdBy:Beth Roberts address.updatedBy:Beth Roberts address.createdByEmail:beth.roberts@winwin.care address.updatedByEmail:beth.roberts@winwin.care programs: notes: datasets: resources: regionServed: spi: sdg: _id:organization_100001 _type:organization _index:winwin _score:1

ID:100002
businessModel: - contactInfo: - createdAt:1,570,076,673,991 updatedAt:1,570,076,673,991 createdBy:Beth Roberts updatedBy:Beth Roberts createdByEmail:beth.roberts@winwin.care updatedByEmail:beth.roberts@winwin.care ein: - facebookUrl: - instagramUrl: - isActive:true linkedinUrl: - missionStatement: - naics_code: - name:BethTest1 description: - ntee_code: - populationServed: - priority:Normal purpose: - assets: - revenue: - sector: - sectorLevel: - sectorLevelName: - selfInterest: - tagStatus: - twitterUrl: - type: - values: - websiteUrl: - adminUrl:https://stage.winwin.care/organizations/100002 parentId:1 rootParentId:1 parentName:10 Books A Home rootParentName:10 Books A Home

ID: 100003
businessModel: - contactInfo: - createdAt:1,570,076,693,040 updatedAt:1,570,076,693,040 createdBy:Beth Roberts updatedBy:Beth Roberts createdByEmail:beth.roberts@winwin.care updatedByEmail:beth.roberts@winwin.care ein: - facebookUrl: - instagramUrl: - isActive:true linkedinUrl: - missionStatement: - naics_code: - name:Beth Test 
2 description: - ntee_code: - populationServed: - priority:Normal purpose: - assets: - revenue: - sector: - sectorLevel: - sectorLevelName: - selfInterest: - tagStatus: - twitterUrl: - type: - values: - websiteUrl: - adminUrl:https://stage.winwin.care/organizations/100003 parentId:1 rootParentId:1 parentName:10 Books A Home rootParentName:10 Books A Home address.id:4,764 address.city: - address.country: address.county: - address.isActive:true address.state: - address.street: - address.zip: - address.createdAt:1,570,076,693,041 address.updatedAt:1,570,076,693,041 address.createdBy:Beth Roberts address.updatedBy:Beth Roberts address.createdByEmail:beth.roberts@winwin.care address.updatedByEmail:beth.roberts@winwin.care programs: notes: datasets: resources: regionServed: spi: sdg: _id:organization_100003 _type:organization _index:winwin _score:1

**Comment by arvindkhatik012** [comment]
@BethRR We have fixed the issue
