### ISSUE TITLE
SameSite  cookie security issue when refresh screen.

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#688]
Receive the following error in the console when I refresh the page

"A cookie associated with a resource at http://gstatic.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032."

**Comment by arvindkhatik012** [comment]
This console warning is not an error or an actual problem — Chrome is just spreading the word about this new standard to increase developer adoption.

Refer: https://stackoverflow.com/questions/58270663/samesite-warning-chrome-77
