### ISSUE TITLE
Organization Mgmt: Filters not persisting

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#695]
This issue was previously resolved in #268, but has resurfaced. Filters set by the user should persist until the user explicitly clears the filters or when a new instance or session is started.  This means that if the user sets filters and navigates to an org and then back to org management, the filters should still be in place. 

**To Repro:**
1. Apply any filter on the Organization Management page
2. Click on an Organization from the remaining list
3. Navigate back to the Organization Management page by clicking on the "Organization Management" breadcrumb
4. The filter that had been applied is no longer in effect, but should be.

**Comment by sunnytambi** [comment]
Fixed and available on stage.

**Comment by BethRR** [comment]
Confirmed fix on stage
