### ISSUE TITLE
Bulk Upload not working

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#696]
Environment: Stage
Issue: We attempted to upload the attached file (we used a .csv, but have changed to txt for github) twice with no luck. The first time John got a blue message (check slack). The second time I got 404 and 500 errors (see the attached screenshot).

Related issue is the messages/handling for failed uploads: https://github.com/winwinwiki/winwin-frontend/issues/683

[Bulk Upload 11_5_19 MA 501c3.txt](https://github.com/winwinwiki/winwin-frontend/files/3811775/Bulk.Upload.11_5_19.MA.501c3.txt)

![UploadIssue](https://user-images.githubusercontent.com/49886260/68255463-1d40f980-ffe2-11e9-8414-e8c8c308c8c3.png)

**Comment by arvindkhatik012** [comment]
@BethRR we tried to upload the bulk upload file and it worked fine and as I told you in my earlier comments that whenever a org will fail to upload its error details will be there in the status file under comments.

![image](https://user-images.githubusercontent.com/45760420/68366541-9ca50900-0159-11ea-9136-5dde10d5e3a8.png)

https://winwin2016.slack.com/archives/CL45P64BA/p1573108627000600

**Comment by BethRR** [comment]
Right, it worked for us when we tried it yesterday. I guess there are two remaining issues:
1) No notification when it fails -- maybe the error detection process could trap the condition that upload hasn't started within some period of time?
2) It's unclear why it wasn't working and I don't know how to troubleshoot.
