### ISSUE TITLE
Kibana: Reader Space should NOT include the management tools and should land on dashboard

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#697]
Also would be ideal if the user landed directly on the default dashboard rather than the general Kibana page. See attached screenshot
![KIbana_Reader_Issue](https://user-images.githubusercontent.com/49886260/68256279-7d389f80-ffe4-11e9-8f21-12ac940746a0.png)

**Comment by arvindkhatik012** [comment]
@BethRR We have already removed the management tools from the reader space and also previously this was available but the features of management tool were not accessible by the readers.

![image](https://user-images.githubusercontent.com/45760420/68367279-551f7c80-015b-11ea-98d5-a79c0e6d000b.png)

**Comment by BethRR** [comment]
confirmed fix
