### ISSUE TITLE
Child Org Creation Form | Name field: Enter should be disabled

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#698]
Please disable Enter for this particular field to address the issue with the child being deleted when user hits enter after typing in the field deletes the child that the user was attempting to create. 

We should discuss other options if this is not possible without affecting fields in other parts of the application. 

![childOrg_save](https://user-images.githubusercontent.com/49886260/68258380-5df14080-ffeb-11e9-9332-c69b73464d18.png)

**Comment by arvindkhatik012** [comment]
@BethRR We have fixed the issue and now whenever the user hits enter button a new child organization will be created.

**Comment by BethRR** [comment]
Issue was not addressed as outlined in this issue, but we'll accept. In the future, please confer with us if you are changing the fix so we can confirm whether or not the proposed solution is appropriate for the tool's workflow.
