### ISSUE TITLE
Org Mgmt: Incorrect message served when action taken on empty selection

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#699]
On the Org Management screen, if the user clicks on an action without having selected an organization, they should get an error or message that tells the user that nothing was selected. Instead, however, the message the user gets tells them that the database was successfully updated.

Steps to repro:
1) Navigate to org management screen
2) Click on 'Set high priority' without selecting any organization
3) Note the inaccurate message.

**Comment by arvindkhatik012** [comment]
We have fixed the issue.

![image](https://user-images.githubusercontent.com/45760420/68584494-bd48c800-04a5-11ea-89dd-7334e9316152.png)
