### ISSUE TITLE
Org Basic Info |  Revenue field: Unclear handling/error char entered exceeds data definition 

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#700]
If user enters more than 19 characters in the revenue field and then clicks save. They get an unclear error message and the UI displays the incorrect entry as though it has been saved (see screenshot)
If the user refreshes the page, the incorrect entry disappears.

Expected: A meaningful error such as 'Revenue field value exceeds allowed character count and will not be saved. To fix: change value to use 19 characters or less.' 

![revenue_error](https://user-images.githubusercontent.com/49886260/68258870-f936e580-ffec-11e9-9fa0-8265d96c0246.png)

**Comment by arvindkhatik012** [comment]
@BethRR We have fixed the issue and from now whenever the user edit the revenue and assets fields with values greater than 17 digits before a decimal a form error message will be populate.

![image](https://user-images.githubusercontent.com/45760420/68673474-d02ccc80-0579-11ea-9d18-93e25b11fb45.png)
![image](https://user-images.githubusercontent.com/45760420/68673503-e9357d80-0579-11ea-9fcf-2a110546165a.png)

**Comment by BethRR** [comment]
Arvind to update the inline validation to include the limit of # of digits that can be entered in the revenue field.

**Comment by arvindkhatik012** [comment]
@BethRR We have changed the inline validation message which include the limit of  number of digits

**Comment by BethRR** [comment]
Okay, will accept fix. In the future, it would be nice if the client validated and gave the inline feedback ( char limit exceeded) once user enters too many char rather than after they hit save.
