### ISSUE TITLE
Filters behaving unexpectedly/inconsistently 

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#703]
**Steps to Repro:**
1. Navigate to org mgmt screen -- note that there are 4,532 organizations found
2. Filter by City for 'Tac' -- note that you now have 11 orgs
3. Change Sector filter to 'Social' -- note that you now have 2 orgs
4. Remove 'Tac' filter  -- note that you have 2,859 orgs
5. Change Sector filter to 'All' -- note that you have 11 orgs, at this point you have no active filters so you should have 4,532 organizations found

**Comment by sunnytambi** [comment]
Fixed in stage.

**Comment by BethRR** [comment]
Confirmed fix in stage
