### ISSUE TITLE
'2 of 3 Shards failed' error when trying to view data table in Kibana

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#704]
When trying to view https://wiki-stage.winwin.care/s/admin/goto/5cb059e7bb6d7fc74740dd6fa355cda2 
user gets 3 instances of  '2 of 3 shards failed' (see attached screenshots)

Please note that though the error messages in the console make reference to inline scripting, we've done no inline scripting when making this table. It's a straight ahead data table.

**Errors and messages from Chrome Console**
PN: No user data, so won't init
kibana:372 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'nonce-tJxzoDXkKucLyG90'". Either the 'unsafe-inline' keyword, a hash ('sha256-SHHSeLc0bp6xt4BoVVyUy+3IbVqp3ujLaR+s+kSP5UI='), or a nonce ('nonce-...') is required to enable inline execution.
bootstrap.js:10 ^ A single error about an inline script not firing due to content security policy is expected!
vendors.bundle.dll.js:600 INFO: 2019-11-06T16:14:08Z
Adding connection to https://wiki-stage.winwin.care/s/admin/elasticsearch
2commons.bundle.js:3 [Violation] 'setInterval' handler took 50ms

![Shards_Failed](https://user-images.githubusercontent.com/49886260/68316694-b9b0dd80-006e-11ea-8f29-c27bab3c76cb.png)

**Comment by arvindkhatik012** [comment]
@BethRR This is an warning not an error  please refer: 
https://discuss.elastic.co/t/5-of-30-shards-failed-in-elastic-5-5-1/162373

**Comment by BethRR** [comment]
Can you confirm what the fix was? I was seeing this when running searches and all errors were related to the vendor bundle dll

**Comment by BethRR** [comment]
I am still regularly seeing this issue. Saying this is a warning is not acceptable as it seems to have data quality implications. Moving back to ToDo and marking as blocked as this issue may ( or may not) be resolved or may change when we restructure the elastic index.

**Comment by sunnytambi** [comment]
@BethRR , there is no data loss or data query related issues with this.
I am currently marking this issue as "deferred", however if you come across data loss or related issues, please feel free to reopen this issue.
