### ISSUE TITLE
Dashboard times out - error related to vendors.bundle.dll.js

### ISSUE THREAD

**Issue by BethRR** [winwinwiki/winwin-frontend#712]
When loading this dashboard: https://wiki-stage.winwin.care/s/admin/goto/6fd3519bec4187eddf485042ecc6a0d6 , we see the following errors:
SearchError: Request Timeout after 30000ms
    at https://wiki-stage.winwin.care/bundles/commons.bundle.js:5:974773
    at processQueue (https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:199747)
    at https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:200710
    at Scope.$digest (https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:210518)
    at https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:213229
    at completeOutstandingRequest (https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:64643)
    at https://wiki-stage.winwin.care/built_assets/dlls/vendors.bundle.dll.js:499:67485

**Comment by arvindkhatik012** [comment]
@BethRR The issue was occured due to fetching large amount of data from the elasticsearch requested by the kibana and the request was taking more than 0.5 minute. We have set the request timeout to 300000ms(5minutes) as previu

**Comment by BethRR** [comment]
I'm concerned about the timeout given the small amount of data -- our entire database is ~98MB and Elastic is designed to easily search shards that are 20-40 GB. It would be good to know what the underlying issue is since truly our queries shouldn't take 30 seconds.

**Comment by sunnytambi** [comment]
Hi @BethRR , this is coming from Elastic/Kibana and not in our control.
