### ISSUE TITLE
Organization Management - Add Program - Outdated breadcrumb feature

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#74]
<img width="1136" alt="Breadrcumb Nonsense" src="https://user-images.githubusercontent.com/48923883/55839783-fa974280-5add-11e9-9d5f-926360307c11.png">

**Comment by akhilesh-94** [comment]
OK, breadcrumb is hidden now

**Comment by BethRR** [comment]
Long term, we need the breadcrumb to function and display correctly. For MVP, it is okay to continue to hide broken breadcrumb.
