### ISSUE TITLE
Organization Management - Org Chart - Function Clarity

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#75]
<img width="1125" alt="Org Chart Function" src="https://user-images.githubusercontent.com/48923883/55840099-1818dc00-5adf-11e9-836c-f8f4b5d8dc4e.png">

**Comment by akhilesh-94** [comment]
The org chart flow is as follows: 

Selected Org(Beverly Hills) -> Divisions(Test Division, new division) -> Departments

Ex. Beverly Hills -> Test Division -> new department

![image](https://user-images.githubusercontent.com/43365228/55870742-db181c80-5ba6-11e9-84e6-77a40c3c51e9.png)
![image](https://user-images.githubusercontent.com/43365228/55870695-be7be480-5ba6-11e9-9b61-61ed0f5403e3.png)

**Comment by BethRR** [comment]
For MVP: Need to change 'Department' to Office For long term: need to be able to edit the labels for any level of the hierarchy to match the org's ( Beth to define)
