### ISSUE TITLE
SPI Tags Doubling

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#77]
![SPI Tag Doubling](https://user-images.githubusercontent.com/48923883/55840242-9f664f80-5adf-11e9-8362-3e110d503e24.png)

**Comment by BethRR** [comment]
This issue has not been resolved. Appears to also be an issue with SDG. It's very inconsistent as some tags seem NOT to duplicate. We haven't been able to determine the difference or root cause for the inconsistent duplicate display issue.
