### ISSUE TITLE
Menu Links

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#78]
![Menu Links](https://user-images.githubusercontent.com/48923883/55840536-9033d180-5ae0-11e9-9577-e6679ffb759f.png)

**Comment by akhilesh-94** [comment]
Will be hiding those options for now from Menu.

**Comment by JRWinWin** [comment]
1. Where can we change the status on the 'Basic Info' page?
2. Ok

**Comment by BethRR** [comment]
The 'fix' that removed Add Child Organization from the menu creates issues for create child orgs. Beth to log additional issues.
