### ISSUE TITLE
Organization Management - Filter Pop Up

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#94]
![Org Management Filter Pop Up](https://user-images.githubusercontent.com/48923883/55973743-0ba99600-5c3b-11e9-8f18-5662c7225468.png)

**Comment by akhilesh-94** [comment]
Duplicate of #23

**Comment by JRWinWin** [comment]
Do you need the NTEE/NAICS reference lists?

**Comment by akhilesh-94** [comment]
> Do you need the NTEE/NAICS reference lists?

@sunnytambi Could you weigh in on this?

**Comment by akhilesh-94** [comment]
> Do you need the NTEE/NAICS reference lists?

Yes, we will be needing the reference lists

**Comment by BethRR** [comment]
confirmed fix
