### ISSUE TITLE
Instagram Field

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#97]
![Instagram Field](https://user-images.githubusercontent.com/48923883/55975211-51b42900-5c3e-11e9-9e49-d1c2fb9b3913.png)

**Comment by akhilesh-94** [comment]
@JRWinWin We will add it post MVP
cc: @sunnytambi @arvindkhatik012

**Comment by JRWinWin** [comment]
I know Sunny and I had discussed this issue previously, but if it is not a significant amount of time to change, can we add the Instagram field to the MVP?
